### ISSUE TITLE
Ability to filter AllLookupsFilter lookups

### ISSUE THREAD

**Issue by stevelacey** [philipn/django-rest-framework-filters#103]
I don't see this as something that can be done currently, wonder if it's worth adding.

Ability to filter the lookups added by `AllLookupsFilter` i.e. I want most, and I want them to follow "the convention" (`__gte` etc) but I don't want to define each, passing a list like `['eq','gte','lte']` would make sense to me?

- I want to limit what I support over my API to only useful actions – because I'll have to support them moving forward, no BC breaks etc
- `AllLookupsFilter` does a good job of filling the filter panel in the browsable API otherwise

If this is useful… maybe making another class and calling it something else would be a good idea, `AllLookupsOhButNotActuallySorryFilter` 😉

**Comment by stevelacey** [comment]
I should RTFM https://github.com/carltongibson/django-filter#usage – though maybe this syntax should be duped here as I skipped learning how to use that library given yours is better.

**Comment by rpkilby** [comment]
I typically recommend using the `Meta.fields` dict syntax over `AllLookupsFilter`. 

Keep in mind that `AllLookupsFilter` only exposes filters for registered lookups on the model field. eg, it would not expose date/time lookups for a number field.
