### ISSUE TITLE
Do filters work with empty strings?

### ISSUE THREAD

**Issue by jsmedmar** [philipn/django-rest-framework-filters#104]
I tried to do 'myfield!=&' and `""` values where not excluded. Is this expected?

**Comment by rpkilby** [comment]
Yep. This is because HTML forms submit all inputs, regardless of their value. It's not possible to distinguish between an empty input and an input with a blank value. 

My suggestion is to create a custom filter that is conceptually similar to the boolean filter used for [`isnull`](https://github.com/carltongibson/django-filter/blob/0.14.0/django_filters/filterset.py#L511-L516) lookups. Something like the following. Keep in mind that you'll need to handle empty values and queryset exclude vs. filter (!= and =). 

```py
from django.core.validators import EMPTY_VALUES

class EmptyStringFilter(filters.BooleanFilter):
    def filter(self, qs, value):
        if value in EMPTY_VALUES:
            return qs

        # semi confusing.
        # myfield__isempty=true => qs.filter(myfield="")
        # myfield__isempty=false => qs.exclude(myfield="")
        # myfield__isempty!=true => qs.exclude(myfield="")
        # myfield__isempty!=false => qs.filter(myfield="")
        exclude = self.exclude ^ (value is False)
        method = qs.exclude if exclude else qs.filter

        return method(**{self.name: ""})
          

class MyFilterSet(filters.FilterSet):
    myfield__isempty = EmptyStringFilter(name='myfield')

    class Meta:
        model = MyModel
```

```http
GET http://localhost/api/my-model?myfield__isempty=false
```

**Comment by rpkilby** [comment]
Also, you could probably create a custom lookup similar to [IsNull](https://github.com/django/django/blob/master/django/db/models/lookups.py#L463-L473), which would allow you to use the `Meta.fields` option. eg,

```py
class MyFilterSet(filters.FilterSet):
    class Meta:
        model = MyModel
        fields = {
            'myfield': ['exact', 'isempty', ...],
        }
```

**Comment by rpkilby** [comment]
Closing this, as it'd be a more appropriate addition to the core library.

**Comment by thalelinh** [comment]
There's this segment for anyone interested in creating their own filters (as far as I'm aware, the recommended solution to this)
http://rpkilby.github.io/django-filter/guide/tips.html#filtering-by-empty-values

**Comment by rptmat57** [comment]
Another way to do this is creating a custom "isempty" lookup which will apply to all fields
https://stackoverflow.com/questions/844556/how-to-filter-empty-or-null-names-in-a-queryset/67751448#67751448
