### ISSUE TITLE
Failures in test_deprecations.py with django-filter 0.14

### ISSUE THREAD

**Issue by edmorley** [philipn/django-rest-framework-filters#106]
The changes in #101 were passing when the PR was opened:
https://travis-ci.org/philipn/django-rest-framework-filters/builds/149494990

However failed once merged to master, under Python 3.4/3.5 only:
https://travis-ci.org/philipn/django-rest-framework-filters/builds/158502234

No other changes landed between the two, so it must be due to external unpinned dependencies changing.

Looking at the logs I see the former used django-filters 0.13, and the latter 0.14. The changes between the two are:
https://github.com/carltongibson/django-filter/compare/v0.13...0.14.0
...which includes some new deprecations.

**Comment by rpkilby** [comment]
Yep the 0.14.0 deprecations would explain it, although I'm confused about why this only affects the python 3.4 and 3.5 builds.
