### ISSUE TITLE
Unable to filter by id

### ISSUE THREAD

**Issue by vaibhav-jain** [philipn/django-rest-framework-filters#118]
I have to explicitly add the `id` field to the filter set otherwise it will not filter by `id` any reason or Am I doing something wrong ???

```
class StudentFilter(drf_filters.FilterSet):
    id = drf_filters.AllLookupsFilter()

    class Meta:
        model = Student
```

**Comment by chozabu** [comment]
I'd noticed the same thing, not sure if it is a bug, or security feature though

**Comment by rpkilby** [comment]
Yeah - that's a bug. The `AllLookupsFilter` isn't being overridden by the 'exact' filter. For the short term, you can just do:

```py
class StudentFilter(drf_filters.FilterSet):
    class Meta:
        model = Student
        fields + {
            'id': '__all__'
        }
```

**Comment by rpkilby** [comment]
I've added a test, but it looks like this had already fixed on the master branch by 64b9c102899131eb0ffa150f99cb737e34467ad8. Could you checkout master and verify that this is indeed fixed?

**Comment by rpkilby** [comment]
Pretty sure this has been fixed. Closing pending feedback.

**Comment by vaibhav-jain** [comment]
@rpkilby Even after upgrading to `0.8.1`  not working.

And
```
class StudentFilter(drf_filters.FilterSet):
    class Meta:
        model = Student
        fields = {
            'id': '__all__'
        }
```

By this you meant I should explicitly specify all the model fields with required filters ??? Well I am stuck with 
```

class StudentFilter(drf_filters.FilterSet):
    id = drf_filters.AllLookupsFilter()

    class Meta:
        model = Student
```

As I don't want to specify every Model field explicitly. . . .

**Comment by chozabu** [comment]
@vaibhav-jain @rpkilby as far as I understand - this is indeed just about filtering by ID by default and saving a little typing & thinking

Currently I have ` id = drf_filters.AllLookupsFilter()` in most of my filters, but it should be dooable to inherit it like this?
```
class BaseFilterSet(drf_filters.FilterSet):
    id = drf_filters.AllLookupsFilter()

class StudentFilter(BaseFilterSet):
    class Meta:
        model = Student

class TeacherFilter(BaseFilterSet):
    class Meta:
        model = Student
```

**Comment by vaibhav-jain** [comment]
@chozabu yes I know I have to do this.  I opened this issue to find out why 'id' isn't included by default.

**Comment by rpkilby** [comment]
In short, explicit is preferred to implicit. If filtering by a model's PK is included by default, how would a user disable that if they wanted to?

Additionally, the difference in effort is minimal:
```py
# implicit PK filter by default
class UserFilterSet(drf_filters.FilterSet):
    class Meta:
        model = User

# explicit filter declaration
class UserFilterSet(drf_filters.FilterSet):
    id = drf_filters.AllLookupsFilter()

    class Meta:
        model = User
```

**Comment by vaibhav-jain** [comment]
Yes @rpkilby I agree.  thanks guys for the help . . .
