### ISSUE TITLE
Consider merging this back to django-filter

### ISSUE THREAD

**Issue by thedrow** [philipn/django-rest-framework-filters#12]
Now that django-filter has an active maintainer I don't see a reason why it shouldn't be reviewed and accepted.

**Comment by rpkilby** [comment]
Hi @thedrow. I don't know if @carltongibson wants to weigh in, but my initial thinking is that it makes more sense for this package to remain separate. The primary reason is that this package's performance is tied to the included DRF backend. Related filterset evaluation is fairly expensive, and the backend gets around this by caching the fully evaluated filtersets. Without the backend caching, the response time basically doubles.

That all said, alex/django-filter#275 and tomchristie/django-rest-framework#3371 might represent a good opportunity to merge this code back in. Closing this for now, but am more than happy on coordinating with @carltongibson on a PR for django-filter.

**Comment by carltongibson** [comment]
I'm all for combining effort. :-)
