### ISSUE TITLE
Deprecate AllLookupsFilter in favor of Meta.fields '__all__'

### ISSUE THREAD

**Issue by rpkilby** [philipn/django-rest-framework-filters#121]
Hi @philipn - wanted to get your opinion on deprecating `AllLookupsFilter` before a 1.0 release. We currently have two ways of exposing all lookups:
- `some_field = filters.AllLookupsFilter()`
- `Meta.fields = {'some_field': '__all__'}` 

My thoughts on this:
- They are functionally identical for the end user
- This [entire section](https://github.com/philipn/django-rest-framework-filters/blob/v0.8.1/rest_framework_filters/filterset.py#L54-L83) of code is dedicated to supporting just `AllLookupsFilter` and requires duplicating some code from the main `django_filters` package. 
- "There should be one obvious way to do it."

**Comment by rpkilby** [comment]
Actually, there are a couple of reasons:
- You can use `AllLookupsFilter` w/o Meta.fields or when Meta.fields is using the list syntax
- You can use `AllLookupsFilter` as part of a mixin filter. Meta option don't work as well for this case. eg
  ```py
  ```

**Comment by jsmedmar** [comment]
The name aliasing feature is crucial... How could this be addressed using `Meta.fields`?

**Comment by rpkilby** [comment]
Yep - I realized this after the fact. See my second comment above. Definitely keeping `AllLoookupsFilter`.
