### ISSUE TITLE
Template rendering fails by default

### ISSUE THREAD

**Issue by one4many** [philipn/django-rest-framework-filters#126]
In backend.py you blindly do this: `template = loader.get_template(self.template)`
This fails per default with the current django_flilters package.
django_filters defines template as 'django_filters/rest_framework/form.html' (or 'django_filters/rest_framework/crispy_form.html' when crispy forms are installed) but does NOT ship the form.html file anywhere. Instead it has a fallback to a static form in it's own backend.py file.

```
try:
    template = loader.get_template(self.template)
except TemplateDoesNotExist:
    template = Template(template_default)'
```

You should do the same and import template_default from django_filters.rest_framework

Regards, Alex

**Comment by rpkilby** [comment]
Hi @one4many - thanks for reporting. The backend code changed a little when migrating it from DRF to `django-filter.rest_framework`. I forgot to make the corresponding changes to the backend here. 

For now, you should be able to safely set the `Backend.template` to `'rest_framework/filters/django_filter.html'` or the crispy-forms alternative. DRF still ships these templates and will continue to do so until at least 3.6/3.7.

**Comment by george-silva** [comment]
having the same issue here. Where is that this code should be changed? in backend.py?

I hate monkey-patching :-1:

**Comment by rpkilby** [comment]
You don't have to monkey patch - you can always inherit and change the path.

```py
from rest_framework_filters import backends

class MyBackend(backends.c):
    template = 'template/path.html'
```

**Comment by rpkilby** [comment]
This should be fixed on master.
