### ISSUE TITLE
enhancement: Invalid Filter Error

### ISSUE THREAD

**Issue by jsmedmar** [philipn/django-rest-framework-filters#130]
Morning gentlemen.

Wondering if there is a way to raise an error when the user tries to use an invalid filter?

Say:

`&color=red`

But color isn't a filter field. I feel this might be trivial, but I'm not seeing it :/

I was thinking as well that this might fail because of other query parameters such as `format`... 

Perhaps, filter validation should happen on the clients end?

**Comment by rpkilby** [comment]
Hi @jsmedmar. Yep - this isn't really possible since that would preclude using other features such as pagination. eg, 

```http
GET http://localhost/api/companies?name__startswith=Acme&page=2
```

**Comment by jsmedmar** [comment]
Yeah, totally agree. I think I'll just have an API endpoint serving valid filters for a given model and then use that for validation on the client side.

Let's close this issue.
