### ISSUE TITLE
templates 

### ISSUE THREAD

**Issue by moniq** [philipn/django-rest-framework-filters#135]
Where can I find template django_filters/rest_framework/crispy_form.html ?

After adding REST backend  'rest_framework_filters.backends.DjangoFilterBackend', I have error:

Django Version: 	1.8.13
Exception Type: 	TemplateDoesNotExist
Exception Value: 	
django_filters/rest_framework/crispy_form.html

Where could I find this missing template? Could you give me some hint?

Packages:
Django==1.8.13
django-crispy-forms==1.4.0
djangorestframework==3.3.3
djangorestframework-filters==0.9.0
django-filter==0.15.3

**Comment by rpkilby** [comment]
Hi @moniq, sorry for the release bug. This has already been fixed on master - see #126 for context.
