### ISSUE TITLE
django-filter made it to 1.0 and it's not backward compatible

### ISSUE THREAD

**Issue by yardensachs** [philipn/django-rest-framework-filters#143]
So 'django-filter>=0.15.0', on the setup.py is bad

**Comment by AmineYaiche** [comment]
I had the same issue.

**Comment by rpkilby** [comment]
Yep - a 1.0 compatible version has been in the works.

**Comment by rpkilby** [comment]
Note that this has been fixed on master, but it might take some time for a new release to be made.
