### ISSUE TITLE
Request based filtering?

### ISSUE THREAD

**Issue by AndrewPashkin** [philipn/django-rest-framework-filters#149]
> The `FilterSet` may be initialized with an optional `request` argument. If a `request` object is passed, then you may access the `request` during filtering. This allows you to filter by properties on the request, such as the currently logged-in user or the Accepts-Languages header.

http://django-filter.readthedocs.io/en/develop/guide/usage.html?highlight=request#request-based-filtering

It seems like this feature is not supported. I thing it's a good idea to introduce it.

**Comment by rpkilby** [comment]
Fixing this should be fairly straightforward:
- The backend needs to initialize the filterset with the request
- The related filtersets need to be initialized with the parent's filterset
- Tests should demonstrate failure for the main filterset and related filtersets

I'm currently in the process of refactoring some of the internals - this will be included as part of that.
