### ISSUE TITLE
Date lookup types do not work (year, day, ...)

### ISSUE THREAD

**Issue by houkk** [philipn/django-rest-framework-filters#15]
2015-02-10 format,__year failure

**Comment by rpkilby** [comment]
Hi @houkk, can you provide more details about the issue you're having? I'm assuming that you mean that year lookups are failing. ie,  `/api/foos?date_created__year=2015`

**Comment by rpkilby** [comment]
This is similar to `isnull`, where the original value type (eg, auto-incrementing integer for relationships) differs from the isnull lookup's value type (boolean).

**Comment by rpkilby** [comment]
Hi @houkk, django-filter v0.13.0 now supports `in` & `range` csv lookups, as well as date transforms. There should be a new drf-filters release soon (v0.8.0) that is compatible with these updates.
