### ISSUE TITLE
give me error when I use "MongoModelViewSet using rest-framework-mongoengine

### ISSUE THREAD

**Issue by KiranPrajapati345** [philipn/django-rest-framework-filters#156]
Here is my code 

```py
import django_filters
import django_filters.rest_framework

from rest_framework_mongoengine.viewsets import ModelViewSet as MongoModelViewSet
from app.serializers import *
from rest_framework_mongoengine.generics import *    
from rest_framework import filters    

from rest_framework.filters import SearchFilter
from django_filters import Filter,CharFilter
from django_filters.fields import Lookup
from rest_framework import generics,filters
def index_view(request):
    context = {}
    return TemplateResponse(request, 'index.html', context)


class ListFilter(CharFilter):
    def sanitize(self, value_list):
        return [v for v in value_list if v != u'']

    def customize(self, value):
        return value

    def filter(self, qs, value):
        multiple_vals = value.split(u",")
        multiple_vals = self.sanitize(multiple_vals)
        multiple_vals = map(self.customize, multiple_vals)
        actual_filter = django_filters.fields.Lookup(multiple_vals, 'in')
        return super(ListFilter, self).filter(qs, actual_filter)

class ListIntegerFilter(ListFilter):
    def customize(self, value):
        return int(value)

class ToolFilterSet(django_filters.FilterSet):
    crop = ListFilter(name='fruit',)
    district = ListFilter(name='district',)
    taluka = ListFilter(name='taluka',)
    class Meta:
        model = Tool
        fields = ['crop','district','taluka',]



class ToolViewSet(MongoModelViewSet):
    queryset = Tool.objects.all()
    model=Tool
    serializer_class = ToolSerializer
    filter_backends = (django_filters.rest_framework.DjangoFilterBackend,SearchFilter,filters.OrderingFilter,)
    filter_class = ToolFilterSet
    search_fields=['crop','district','taluka',]  
    ordering_fields = '__all__'
```

this is code:
and I got the error :  
AttributeError: 'MetaDict' object has no attribute 'get_field'

So, how can I filter my multiple fields value?
How can I get then if someone want data for  http://tool/?district=Pune,Nasik    using rest-framework-filters I have data stored in mongodb.

Edited for formatting (@rpkilby)

**Comment by rpkilby** [comment]
Hi @KiranPrajapati345. Do you have a more complete stack trace? There isn't too much that can be done to help you without it. 

Keep in mind that `django-filter` and `django-rest-framework-filters` are designed to work with the Django ORM. It looks like `mongoengine` uses the same queryset API as the Django ORM, so there might be a minimal amount of compatibility, however this compatibility is neither guaranteed nor tested against. 

As to the issue, my guess here is that the filterset is failing to introspect your document model, since mongoengine does not conform to the same meta API as the Django ORM. You *might* be able to get this to work by removing the `fields` option from your `ToolFilterSet.Meta` class.

**Comment by KiranPrajapati345** [comment]
Hi @rpkilby ,Here is my code

1)models.py file

from django.db import models
from mongoengine import Document, fields

class Tool(Document):
    id = fields.StringField(required=True)
    year = fields.IntField(required=True)
    crop = fields.StringField(required=True)
    district = fields.StringField(required=True)
    taluka = fields.StringField(required=True)
    circle = fields.StringField(required=True)
    ay05 = fields.FloatField(required=True)

    def __str__(self):
    	return self.crop
    
    def save(self,*args, **kwargs):
    	super().save(*args, **kwargs)

    class Meta:
    	verbose_name_plural ='tool'

2) Serializers.py file : 

from rest_framework import serializers
from rest_framework_mongoengine import serializers as mongoserializers

from models import Tool

class ToolSerializer(mongoserializers.DocumentSerializer):

    class Meta:
        model = Tool
        fields=('id','crop','district','taluka',year','circle',ay05',)

3) views.py file : 

import django_filters
import django_filters.rest_framework

from rest_framework_mongoengine.viewsets import ModelViewSet as MongoModelViewSet
from app.serializers import *
from rest_framework_mongoengine.generics import *    
from rest_framework import filters    

from rest_framework.filters import SearchFilter
from django_filters import Filter,CharFilter
from django_filters.fields import Lookup
from rest_framework import generics,filters
def index_view(request):
    context = {}
    return TemplateResponse(request, 'index.html', context)


class ListFilter(CharFilter):
    def sanitize(self, value_list):
        return [v for v in value_list if v != u'']

    def customize(self, value):
        return value

    def filter(self, qs, value):
        multiple_vals = value.split(u",")
        multiple_vals = self.sanitize(multiple_vals)
        multiple_vals = map(self.customize, multiple_vals)
        actual_filter = django_filters.fields.Lookup(multiple_vals, 'in')
        return super(ListFilter, self).filter(qs, actual_filter)

class ListIntegerFilter(ListFilter):
    def customize(self, value):
        return int(value)

class ToolFilterSet(django_filters.FilterSet):
    crop = ListFilter(name='crop',)
    district = ListFilter(name='district',)
    taluka = ListFilter(name='taluka',)
    class Meta:
        model = Tool
        fields = ['crop','district','taluka',]



class ToolViewSet(MongoModelViewSet):
    queryset = Tool.objects.all()
    model=Tool
    serializer_class = ToolSerializer
    filter_backends = (django_filters.rest_framework.DjangoFilterBackend,SearchFilter,filters.OrderingFilter,)
    filter_class = ToolFilterSet
    search_fields=['crop','district','taluka',]  
    ordering_fields = '__all__'

Then It's gives me error .
AttributeError: 'MetaDict' object has no attribute 'get_field'

And when I remove fields options in ToolFilterSet.Meta class. then
when I run  http://127.0.0.1/8000  it's gives another error 
"type object 'ToolFilterSet' has no attribute 'Meta'   "

**Comment by KiranPrajapati345** [comment]
And same code for views.py file I use for another project (without mongoengine) then it's working
for example:  suppose someone search fruit=Guava,Banana,Pomegranate
then data will shows only this 3 fruits output ..

here is my views.py file for another project (without using mongoengine)

import django_filters
import django_filters.rest_framework
from rest_framework.viewsets import ModelViewSet
from WBCIS.serializers import WbcisSerializer
from WBCIS.models import Wbcis 
from rest_framework import generics,filters
from rest_framework.filters import SearchFilter
from django_filters import Filter,CharFilter
from django_filters.fields import Lookup

class ListFilter(CharFilter):
    def sanitize(self, value_list):
        return [v for v in value_list if v != u'']

    def customize(self, value):
        return value

    def filter(self, qs, value):
        multiple_vals = value.split(u",")
        multiple_vals = self.sanitize(multiple_vals)
        multiple_vals = map(self.customize, multiple_vals)
        actual_filter = django_filters.fields.Lookup(multiple_vals, 'in')
        return super(ListFilter, self).filter(qs, actual_filter)

class ListIntegerFilter(ListFilter):
    def customize(self, value):
        return int(value)

class WbcisFilterSet(django_filters.FilterSet):
    fruit = ListFilter(name='fruit',)
    district = ListFilter(name='district',)
    sum_insured=ListIntegerFilter(name='sum_insured',)
    #max_farmer = django_filters.NumberFilter(name="farmer", lookup_expr='lte')
    class Meta:
        model = Wbcis
        fields = ['fruit','district','taluka','sum_insured',]

class WbcisViewSet(ModelViewSet):
    queryset = Wbcis.objects.all()
    model=Wbcis
    serializer_class = WbcisSerializer
    filter_backends = (django_filters.rest_framework.DjangoFilterBackend,SearchFilter,filters.OrderingFilter,)
    filter_class = WbcisFilterSet
    search_fields=['fruit','district','taluka','revenue_circle','farmer','area','sum_insured',]  
    ordering_fields = '__all__'

So, can you tell me what's wrong in MongoModelViewSet ?

**Comment by rpkilby** [comment]
> And when I remove fields options in ToolFilterSet.Meta class. then
> when I run http://127.0.0.1/8000 it's gives another error
> "type object 'ToolFilterSet' has no attribute 'Meta' "

1. Did you delete the entire `Meta` class or did you just remove the fields option
2. Could you post the *full* stack trace?

**Comment by KiranPrajapati345** [comment]
Hi, I solved this issue, I use dynamic query for my project.
Queryset(self,arg,kwargs).

Its working now
Thanks


On Jan 3, 2017 10:29 PM, "Ryan P Kilby" <notifications@github.com> wrote:

And when I remove fields options in ToolFilterSet.Meta class. then
when I run http://127.0.0.1/8000 it's gives another error
"type object 'ToolFilterSet' has no attribute 'Meta' "


   1. Did you delete the entire Meta class or did you just remove the
   fields option
   2. Could you post the *full* stack trace?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/philipn/django-rest-framework-filters/issues/156#issuecomment-270163787>,
or mute the thread
