### ISSUE TITLE
README DRF versions are outdated (3.3, 3.4 => 3.4, 3.5)

### ISSUE THREAD

**Issue by Jaredn** [philipn/django-rest-framework-filters#159]
Just wondering if this is DRF 3.5.x compatible.  Documentation says 3.3 and 3.4.

Thanks!

**Comment by rpkilby** [comment]
Yep: https://github.com/philipn/django-rest-framework-filters/blob/master/.travis.yml#L13

**Comment by Jaredn** [comment]
Quick Question for you... Say I have a simple model that looks like this:

Room   ---->    Building    ---->    Site

May rooms in a building, many buildings in a site.

I want the following api call to work:
/api/rooms/?buiding__site__name__startswith=blah

In english:  Give me all of the rooms that are contained within sites that
have names starting with ^blah.

How do I properly build the filtersets?  I can not figure this out for the
life of me, as all examples seem to work in the reverse direction, like
trying to find sites that contain a room called 'blah'.  I know basic
DjangoRestFilter can do this if I simply add the fields as you see above to
filter_fields, but I have way too many relationships to list them all, and
I was hoping to have better control of what special django filters I can
use (startswith, gte, lte, etc).

Thanks!

**Comment by rpkilby** [comment]
You should be able to accomplish that with:

```py
# models
class Site(models.Model):
    ...

class Building(models.Model):
    site = models.ForeignKey(Site, on_delete=models.CASCADE)
    ...

class Room(models.Model)
    site = models.ForeignKey(Building, on_delete=models.CASCADE)
    ...

# filters
class SiteFilter(filters.FilterSet):
    class Meta:
        model = Site
        fields = {'name': ['startswith'], }

class BuildingFilter(filters.FilterSet):
    site = filters.RelatedFilter(SiteFilter)

    class Meta:
        model = Building

class RoomFilter(filters.FilterSet):
    building = filters.RelatedFilter(BuildingFilter)

    class Meta:
        model = Room
```

**Comment by Jaredn** [comment]
Thanks for the response on this thread @rpkilby!   I could have sworn that's what I tried, but I'll give it a shot as soon as I can (troubleshooting a different DRF issue now though).
