### ISSUE TITLE
Release a version with Django 1.11 support

### ISSUE THREAD

**Issue by edmorley** [philipn/django-rest-framework-filters#163]
Hi!

Django 1.11 beta 1 has just been released:
https://www.djangoproject.com/weblog/2017/feb/20/django-111-beta-1-released/

It would be great if the recent Django 1.11 compatibility fixes on master (eg supporting django-filter >1.0) could be released so we could start testing with Django 1.11 on our projects without needing to install from master.

Many thanks :-)

**Comment by rpkilby** [comment]
Thanks - currently waiting for the 1.2 release of django-filter

**Comment by mjschultz** [comment]
Looks like [django-filter==1.0.2](https://pypi.python.org/pypi/django-filter/1.0.2) is out as is [django==1.11](https://pypi.python.org/pypi/Django/1.11)!

**Comment by edmorley** [comment]
Does the django-filter requirement in setup.py need incrementing from 1.0.0 to 1.0.2, or are the 1.0.0->1.0.2 changes just a nicety (ignoring Django 1.11 support) and not technically required for the next d-r-f-filters release for say Django 1.10?
https://github.com/philipn/django-rest-framework-filters/blob/b5ccd8a41ce5ba155afe5ca8e04ff79f5286bb0b/setup.py#L46

**Comment by rpkilby** [comment]
There should be no API surface changes that drf-filters would care about. I don't believe there is a benefit to specifying. That said, it wouldn't hurt either. 

In regards to creating a new release, the current state of drf-filters is that it is django-filter 1.x and django 1.11 compatible, and all of our internal deprecations have been removed. We could probably cut a 0.10.0 release in it's current state and then followup with a 1.0 release when the filtering logic has been replaced with the subquery approach.

**Comment by rpkilby** [comment]
See #167

**Comment by hamstap85** [comment]
I'm still confused. How was this resolved? What `djangorestframework` versions support Django 1.11?

**Comment by rpkilby** [comment]
drf-filters 0.10 is compatible with django-filter 1.0, which is in turn compatible with django 1.11

In general, drf-filters is tested against the latest two versions of DRF and the latest version of django-filter.

**Comment by hamstap85** [comment]
We don't use drf-filters. There's nothing about any particular version of DRF that would be incompatible with Django 1.11?

**Comment by rpkilby** [comment]
> We don't use drf-filters

DRF-filters is just a shorthand name for djangorestframework-filters

**Comment by hamstap85** [comment]
Yes, we don't use that.

**Comment by rpkilby** [comment]
Then you are in the wrong place. This is the issue tracker for djangorestframework-filters, not DRF.

**Comment by hamstap85** [comment]
Well darn. I was mistakenly linked here. Completely did not see "-filters" on the repo name. Sorry.

**Comment by rpkilby** [comment]
No worries. 😄
