### ISSUE TITLE
Key error when using Negation/Exclusion

### ISSUE THREAD

**Issue by weasteam** [philipn/django-rest-framework-filters#164]
`?id!=1` and I got Key error

```
Exception Type:	KeyError
Exception Value:	
'id!'
```

I set it up according to https://github.com/philipn/django-rest-framework-filters, did I miss something?

**Comment by rpkilby** [comment]
This is difficult to debug without a more complete example. Could you provide the code for your `FilterSet`?

**Comment by weasteam** [comment]
import rest_framework_filters as filters
```
class MyFilter(filters.FilterSet):
    model = MyModel
    fields = {'id':['exact','lt','gt','gte','lte']}
```

**Comment by rpkilby** [comment]
`model` and `fields` should be located under the `Meta` options class.

```python
class MyFilter(filters.FilterSet):
    class Meta:
        model = MyModel
        fields = {'id':['exact','lt','gt','gte','lte']}
```

Let me know if you have further issues.

**Comment by weasteam** [comment]
Sorry,

There was a typo, the `model` and `fields` are actually under the `Meta`.

**Comment by rpkilby** [comment]
Hi @weasteam - this is difficult to debug without more information. Do you have a stack trace for the error?

I did a quick test, and the exclusion seems to work as expected. Below, `data={'id!': '1'}` should be equivalent to a `?id!=1` querystring.

```python
In [1]: from tests.testapp import models
In [2]: import rest_framework_filters as filters
In [3]: class NoteFilter(filters.FilterSet):
   ...:     class Meta:
   ...:         model = models.Note
   ...:         fields = {'id': ['exact', 'lt', 'gt', 'lte', 'gte']}
   ...:         
In [4]: f = NoteFilter(data={'id!': '1'}, queryset=models.Note.objects.all())
In [5]: print(f.qs.query)
SELECT "testapp_note"."id", "testapp_note"."title", "testapp_note"."content", "testapp_note"."author_id" FROM "testapp_note" WHERE NOT ("testapp_note"."id" = 1)
```

**Comment by weasteam** [comment]
**One reason could be python 3.5.2**

Here are the error details:

```
'id!'
Request Method:	GET
Request URL:	http://127.0.0.1:8000/api/substances/list/?id!=1
Django Version:	1.10.5
Exception Type:	KeyError
Exception Value:	
'id!'
Exception Location:	/Users/myname/anaconda/lib/python3.5/site-packages/django_filters/filterset.py in qs, line 335
Python Executable:	/Users/myname/anaconda/bin/python
Python Version:	3.5.2
Python Path:	
['/Users/myname/repositories/knowledgebase',
 '/Users/myname/anaconda/lib/python35.zip',
 '/Users/myname/anaconda/lib/python3.5',
 '/Users/myname/anaconda/lib/python3.5/plat-darwin',
 '/Users/myname/anaconda/lib/python3.5/lib-dynload',
 '/Users/myname/anaconda/lib/python3.5/site-packages',
 '/Users/myname/anaconda/lib/python3.5/site-packages/Sphinx-1.4.6-py3.5.egg',
 '/Users/myname/anaconda/lib/python3.5/site-packages/aeosa',
 '/Users/myname/anaconda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg',
]
Server time:	Thu, 16 Mar 2017 23:02:22 +0000
```

---
/Users/myname/anaconda/lib/python3.5/site-packages/rest_framework_filters/backends.py in filter_queryset
            return filter_class(request.query_params, queryset=queryset).qs ...
▼ Local vars
Variable	Value
filter_class	
<class 'rest_framework_filters.filterset.FilterSet.get_subset.<locals>.FilterSubset'>
queryset	
<QuerySet [<Substance: IBS-013 (Biospecimen)>, <Substance: IBS-013_E1 (Extract)>, <Substance: IBS-013_E1_L1 (Library)>, <Substance: IBS-009 (Biospecimen)>, <Substance: IBS-009_E1 (Extract)>, <Substance: IBS-009_E1_L1 (Library)>, <Substance: IBS-025 (Biospecimen)>, <Substance: IBS-025_E1 (Extract)>, <Substance: IBS-025_E1_L1 (Library)>, <Substance: IBS-028 (Biospecimen)>, <Substance: IBS-028_E1 (Extract)>, <Substance: IBS-028_E1_L1 (Library)>, <Substance: IBS-004 (Biospecimen)>, <Substance: IBS-004_E1 (Extract)>, <Substance: IBS-004_E1_L1 (Library)>, <Substance: IBS-007 (Biospecimen)>, <Substance: IBS-007_E1 (Extract)>, <Substance: IBS-007_E1_L1 (Library)>, <Substance: IBS-024 (Biospecimen)>, <Substance: IBS-024_E1 (Extract)>, '...(remaining elements truncated)...']>
request	
<rest_framework.request.Request object at 0x106f3f0f0>
self	
<rest_framework_filters.backends.DjangoFilterBackend object at 0x106f49048>
view	
<lims.serializers.SubstanceViewSet object at 0x106f02358>

---
/Users/myname/anaconda/lib/python3.5/site-packages/rest_framework_filters/filterset.py in qs
        qs = super(FilterSet, self).qs ...
▼ Local vars
Variable	Value
__class__	
<class 'rest_framework_filters.filterset.FilterSet'>
available_filters	
OrderedDict([('id',
              <django_filters.filters.NumberFilter object at 0x105626a20>)])
requested_filters	
OrderedDict([('id!',
              <django_filters.filters.NumberFilter object at 0x1056cae10>)])
self	
<rest_framework_filters.filterset.FilterSet.get_subset.<locals>.FilterSubset object at 0x1056269b0>
---
/Users/myname/anaconda/lib/python3.5/site-packages/django_filters/filterset.py in qs
                    value = self.form.cleaned_data[name] ...
▼ Local vars
Variable	Value
filter_	
<django_filters.filters.NumberFilter object at 0x1056cae10>
name	
'id!'
qs	
<QuerySet [<Substance: IBS-013 (Biospecimen)>, <Substance: IBS-013_E1 (Extract)>, <Substance: IBS-013_E1_L1 (Library)>, <Substance: IBS-009 (Biospecimen)>, <Substance: IBS-009_E1 (Extract)>, <Substance: IBS-009_E1_L1 (Library)>, <Substance: IBS-025 (Biospecimen)>, <Substance: IBS-025_E1 (Extract)>, <Substance: IBS-025_E1_L1 (Library)>, <Substance: IBS-028 (Biospecimen)>, <Substance: IBS-028_E1 (Extract)>, <Substance: IBS-028_E1_L1 (Library)>, <Substance: IBS-004 (Biospecimen)>, <Substance: IBS-004_E1 (Extract)>, <Substance: IBS-004_E1_L1 (Library)>, <Substance: IBS-007 (Biospecimen)>, <Substance: IBS-007_E1 (Extract)>, <Substance: IBS-007_E1_L1 (Library)>, <Substance: IBS-024 (Biospecimen)>, <Substance: IBS-024_E1 (Extract)>, '...(remaining elements truncated)...']>
self	
<rest_framework_filters.filterset.FilterSet.get_subset.<locals>.FilterSubset object at 0x1056269b0>
valid	
True
value	
None

**Comment by rpkilby** [comment]
Reopening this since there aren't any tests covering form/view usage. 

Also, what versions of django, djangorestframework, django-filter, and djangorestframework-filters are you using?

**Comment by weasteam** [comment]
>>>pip freeze
Django==1.10.5
django-crispy-forms==1.6.1
django-filter==0.15.3
djangorestframework==3.5.3
djangorestframework-csv==2.0.0
djangorestframework-filters==0.9.1


Python 3.5.2

**Comment by rpkilby** [comment]
Hi @weasteam. I've added a test for exclusion filtering at the backend level. At this point, it's not clear to me what's causing the error you're seeing. My recommendation would be to create a sample project that has a minimal example demonstrating the issue. Additionally, it wouldn't hurt to update to the latest versions of the various packages.
