### ISSUE TITLE
Filter by count of children. 

### ISSUE THREAD

**Issue by danilke** [philipn/django-rest-framework-filters#173]
Hello! Is possible to filter by count of children?

 For example: Order has many OrderItems, I want to filter orders with orders count 4? Or I have to save order_items_count attribute to Order model? And how I order by count?

Thanks a lot!

**Comment by rpkilby** [comment]
>  Is possible to filter by count of children?

Sure. You should use a `NumberFilter` with the [`method`](https://github.com/philipn/django-rest-framework-filters#supporting-filtermethod) argument. Using a method/callable, you can do whatever you want with the filterset. Filtering by count is going to require using an aggregation function, but at that point, the question is ORM related and not specific to django-filter
