### ISSUE TITLE
DRY: Allowing __all__ lookups on all fields, fields already defined in serializer

### ISSUE THREAD

**Issue by darkpixel** [philipn/django-rest-framework-filters#175]
In my serializer, I already have:
```
class Meta:
  model = Note
  fields = [
    'id',
    'computer',
    'note',
  ]
```

I would like to allow all lookups on those fields.  In order to do this, I have to define a FilterSet:
```
class Meta:
  model = Computer
  fields = {
    'id': '__all__',
    'computer': '__all__',
    'note': '__all__',
  }
```
Am I missing something?  Is there a way to apply a filterset without re-defining the model and explicitly setting the fields to __all__?

**Comment by rpkilby** [comment]
> Is there a way to apply a filterset without re-defining the model and explicitly setting the fields to __all__?

Not really. FilterSets are derived from models, not serializers. You could create a helper function that creates the filterset fields from the serializer fields, but I don't know if it's worth it.

```python
def all_field_lookups(serializer_class):
    return {f: '__all__' for f in serializer_class.Meta.fields}

class ComputerSerializer(serializers.ModelSerializer):
    class Meta:
        model = Computer
        fields = ['id', 'computer', 'note']

class ComputerFilterSet(filters.FilterSet):
    class Meta:
        model = Computer
        fields = all_field_lookups(ComputerSerializer)
```

Additionally, I'd like to reiterate the admonition in the docs against using `'__all__'`. I'm not incredibly inclined to make usage more easy/automatic.
