### ISSUE TITLE
Changelog section missing for v0.10.1

### ISSUE THREAD

**Issue by edmorley** [philipn/django-rest-framework-filters#176]
Thank you for the new release :-)

There doesn't appear to be a changelog entry for it in:
https://github.com/philipn/django-rest-framework-filters/blob/master/CHANGELOG.rst

From what I can see, #172 was the only change, and was to (a) fix #171, (b) improve performance.

(Having a changelog entry helps when using tools like pyup-bot, since it includes the entry in the PR it opens, but in this case it couldn't find one, eg: mozilla/treeherder#2542)

**Comment by edmorley** [comment]
(Having a changelog entry helps when using tools like pyup-bot, since it includes the entry in the PR it opens, but in this case it couldn't find one, eg: mozilla/treeherder#2542)

**Comment by philipn** [comment]
Thanks for the catch!  We'll be sure to publish a changelog entry for all releases from now on (I published an entry in the GitHub 'releases' tab / associated git tag, but your use case makes a lot of sense).  If we 'fixed' this issue by publishing a new release with a CHANGELOG entry, that could be considered confusing :)

**Comment by edmorley** [comment]
> If we 'fixed' this issue by publishing a new release with a CHANGELOG entry, that could be considered confusing :)

A new release isn't required to update the changelog, tools like pyup use the changelog from master :-)

**Comment by rpkilby** [comment]
As an addendum, I don't think it's worth the effort, but a [post release](https://www.python.org/dev/peps/pep-0440/#post-releases) would be appropriate for this kind of update.
