### ISSUE TITLE
Status of project

### ISSUE THREAD

**Issue by sassanh** [philipn/django-rest-framework-filters#179]
Looking at recent commits seems like it's progressing slowly recently. I'm trying to find a good way for embedding filter sets in each other and `django-rest-framework-filters` has this out of the box. But I wanna know if using it is safe for long time. I know about issues 99 and 100 and those aren't currently a concern for my project as I don't expect anyone to try hacky things till user base grows. I just wanna know is there going to be a version 1 in coming months? Are you planning to work on this project? Few months ago we had a discussion here https://github.com/carltongibson/django-filter/issues/587. It would be great if you could update me with the status of project.

**Comment by philipn** [comment]
@sassanh This project is actively maintained and has enough users that I expect it to stay that way for a while.  I personally haven't contributed much to the project in a while, but @rpkilby has been doing a fantastic job maintaining the package.

I use `django-rest-framework-filters` on https://localwiki.org (~1M monthly users), but I'm not using it on my current project yet.  If/when I do, I expect I'll personally be more active contributing again.

**Comment by sassanh** [comment]
That's good news. Thanks for sharing. I keep it open in case @rpkilby has a note on this.

**Comment by sassanh** [comment]
I started migrating to `django-rest-framework-filters` and it's really cool. Migration from `django-filters` happened in a minute with some global replacements in project and `RelatedFilter` is very nice.

**Comment by sassanh** [comment]
Now i noticed you're repository owner. Sorry. I think I can close it now as your information should be reliable.

**Comment by rpkilby** [comment]
Hi @sassanh - I'm still around as well. Active feature development has been on the back burner for some time, but I'm slowly clearing my plate.

**Comment by sassanh** [comment]
:confused:

**Comment by sassanh** [comment]
Are you going to support Djanog 2.1?

**Comment by philipn** [comment]
Can you open a specific issue with the question, e.g. Support Django 2.1?

**Comment by sassanh** [comment]
Done
