### ISSUE TITLE
Ensure nested relationships are valid for RelatedFilter

### ISSUE THREAD

**Issue by sassanh** [philipn/django-rest-framework-filters#180]
It'd be great if we had same `source` parameter in other `django-filters` filters on `RelatedFilter`. Something like this:
```
    examination = filters.RelatedFilter(
        ExaminationFilter,
        source='students__student__registrations__examination',
        queryset=Examination.objects.all(),
    )
```
So that instead of `/api/school/?students__student__registrations__examination__date__range` I can query `/api/school/?examination__date__range`. "students__student__registrations__" is internal detail that API user doesn't need to know about.

**Comment by rpkilby** [comment]
I believe specifying `name` in this manner already accomplishes this.

**Comment by rpkilby** [comment]
To further clarify, `name` is intended to be the target model field name. You should be able to specify a nested relationship as the name.

**Comment by sassanh** [comment]
That was my assumption too but unfortunately it raises this exception:
```
TypeError: 'Meta.fields' contains fields that are not defined on this FilterSet: <value of name parameter>
```

**Comment by sassanh** [comment]
Other than that I think it'd be better if we keep the api the same as `django-filters` and use `source` for this purpose.

**Comment by rpkilby** [comment]
I've created a test/PR that guarantees this behavior. My guess is that the related name is not using the `related_query_name`, but is instead using the `related_name` of the related object manager.
