### ISSUE TITLE
Using Filter.method with multiple field lookups

### ISSUE THREAD

**Issue by nogurenn** [philipn/django-rest-framework-filters#181]
Is there a canonical/package way to filter a queryset inside `Filter.method` based on certain query parameter lookups? 

The current behavior is that the filter method only triggers if the url query parameter exactly matches the filter calling the method (e.g. `?departure_date=2017-01-01`, but not `?departure_date__<lookup>=2017-01-01`). What I need is for `departure_date` filter to trigger whether it is a single date or two dates separated by a delimiter.

Below is my current implementation that satisfies `?departure_date=2017-01-01`, but I don't know how to modify it to also accept a range of dates without resorting to a `CharFilter`.

``` python
class TripFilterSet(filters.FilterSet):
    departure_date = filters.DateTimeFilter(name='departure_date', method='filter_departure_date')

    class Meta:
        model = Trip
        fields = ('departure_date',)

    def filter_departure_date(self, queryset, name, value):
        lookup = f'{name}__date'
        return queryset.filter(**{lookup: value})
```

**Comment by rpkilby** [comment]
Hi @nogurenn. [`BaseRangeFilter`](https://django-filter.readthedocs.io/en/latest/ref/filters.html#baserangefilter) is exactly what this is intended for.

I'm going to close this since it's a usage question, but feel free to ask followup questions here if necessary.
