### ISSUE TITLE
TypeError: get_filter_name() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by danielhers** [philipn/django-rest-framework-filters#187]
Starting with django-filter 1.1.0 (released today), I get this error. With django-filter 1.0.4 it worked fine.

See carltongibson/django-filter#798, and the failing job [here](https://travis-ci.org/danielhers/UCCA-App/jobs/289970765).

Seems like the problem is with [this line](https://github.com/philipn/django-rest-framework-filters/blob/master/rest_framework_filters/filterset.py#L19), as the backtrace is:

    File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/rest_framework_filters/filterset.py", line 19, in __new__
        new_class = super(FilterSetMetaclass, cls).__new__(cls, name, bases, attrs)
      File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django_filters/filterset.py", line 90, in __new__
        new_class.base_filters = new_class.get_filters()
      File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django_filters/filterset.py", line 320, in get_filters
        filter_name = cls.get_filter_name(field_name, lookup_expr)
    TypeError: get_filter_name() takes 2 positional arguments but 3 were given

**Comment by george-silva** [comment]
same issue here.

does the 1.0.4 version works fine?

**Comment by danielhers** [comment]
Yes, a workaround is to pin django-filter to 1.0.4.

**Comment by george-silva** [comment]
Yep, it worked!

**Comment by rpkilby** [comment]
Hi all, this has been fixed on master. v0.10.2 should be inbound shortly, but if you want django-filter v1.1 compatibility now, you can install 373242f385b368ef4ef96350c001daeb4bc05c9e.

**Comment by rpkilby** [comment]
v0.10.2 is no on pypi

**Comment by george-silva** [comment]
@rpkilby I'll test this shortly and I'll get back!

Thanks!
