### ISSUE TITLE
'range' lookup types do not work

### ISSUE THREAD

**Issue by scottwoodall** [philipn/django-rest-framework-filters#2]
Can you show an example that uses `fieldname__range`? After trying some things myself, googling and browsing source code of this project and `django-filter` I've come up empty handed.

**Comment by rpkilby** [comment]
Hi all, django-filter v0.13.0 now supports `in` & `range` csv lookups, as well as date transforms. There should be a new drf-filters release soon (v0.8.0) that is compatible with these updates.
