### ISSUE TITLE
Filtering on a through model doesn't work as expected?

### ISSUE THREAD

**Issue by RobinRamael** [philipn/django-rest-framework-filters#207]
Hi! 

I have two models: `Medium` and `Hashtag`, which are in a m2m relation with each other. `Medium` also points to another model, `Card`.  

I'm writing an endpoint that now returns the most used hashtags for mediums corresponding to a certain set of filters and trying to do this with `rest_framework_filters.FilterSet`. 

To achieve this, I'm trying to apply a `FilterSet` on a subquery on the m2m through model:

```python

class MediumFilter(filters.FilterSet):

    class Meta:
        model = Medium
        fields = {'card': ['exact'], 'published_at': ['lte', 'gte', 'date']}


class MediumHashtagsFilter(filters.FilterSet):
    medium = filters.RelatedFilter(MediumFilter, queryset=Medium.objects.all())

    class Meta:
        model = Medium.hashtags.through
        fields = ['medium', 'medium__card', 'medium__published_at']  # this works for card, but not published_at


class MostUsedHashtagsViewSet(ReadOnlyModelViewSet):
    permission_classes = (StaffPermission,)
    serializer_class = MostUsedHashtagSerializer
    pagination_class = None
    subquery_filter_class = MediumHashtagsFilter
    limit = 10

    def get_queryset(self):

        subquery_filter = self.subquery_filter_class(self.request.query_params)

        # if not subquery_filter.is_valid():  # unrelated, maybe, but this raises AttributeError: 'MediumHashtagsFilter' object has no attribute 'is_valid'
        if not subquery_filter.form.is_valid() or not subquery_filter.is_bound:
            raise Exception

        subquery = Subquery(
            subquery_filter.qs
            .filter(hashtag_id=OuterRef('pk'))
            .values('hashtag')
            .annotate(count=Count('medium'))
            .values('count'))

        queryset = (
            Hashtag.objects
            .annotate(usage_count=Expr(subquery, output_field=IntegerField()))
            .exclude(usage_count=None)
            .order_by('-usage_count', 'name')
        )

        return queryset[:self.limit]
```
And then calling the endpoint in a test like so:

```python
# this works as expected:
        response = self.client.get(self.url, {
            # 'medium__card': self.card.pk,
            'medium__card': self.card.pk
        })

# but this doesn't:

        response = self.client.get(self.url, {
            'medium__published_at__gte': '2017-01-14',
            'medium__published_at__lte': '2017-01-24'
        })
```
Getting the filtering by `Card` working required a weird fields declaration in the `FilterSet`s `Meta`, but I got it working. Now I'd like to also be able to filter on a range of datetimes, but my solution doesn't work for this case.

After tearing my hair out for the last day, I came to this solution with the `__` in the `Meta.fields` declaration by stepping through the code and seeing that while the data for the underlying form was mapping the filter value to `medium__card`,  the only field name being looked for was `medium` itself. Is this a bug? Am I abusing the library? Am I missing something?

**Comment by rpkilby** [comment]
I haven't finished reading this yet, but the FilterSet `Meta.fields` use seems a bit off. if you define a filterset A and another filterset B with a relation to A, it's not necessary to list A's filters in B's `Meta.fields`. eg,

```python
class AFilter(FilterSet):
    class Meta:
        model = A
        fields = ['field_a', 'field_b']


class BFilter(FilterSet):
    a = filters.RelatedFilter(A, queryset=A.objects.all())

    class Meta:
        model = B
        fields = ['a']  # do this
        fields = ['a', 'a__field_a', 'a__field_b']  # not this
```

**Comment by rpkilby** [comment]
I'm going to have to come back to this later, but my recommendation is to simplify the problem first and work backwards towards your original issue. In this case, the 'most used' subquery seems superfluous to the filtering issues. Try testing your FilterSets directly and ignore the view for now. eg,

```python
# data can either be a QueryDict or a regular dict
f = MediumFilter({'published_at__gte': '2017-01-14', 'published_at__lte': '2017-02-14'})

# view the qs resultset
print(f.qs)

# inspect the SQL statement
print(str(f.qs.query)
```

**Comment by rpkilby** [comment]
I'm going to close this for now. If you can reduce the problem to a minimal example, I'd be happy to take a look at that. Ideally, this would include just models, filtersets, and an example query.
