### ISSUE TITLE
Remove usage of request.QUERY_PARAMS

### ISSUE THREAD

**Issue by cancan101** [philipn/django-rest-framework-filters#21]
`request.QUERY_PARAMS` has been deprecated per: http://www.django-rest-framework.org/topics/3.1-announcement/#deprecations

Usage: https://github.com/philipn/django-rest-framework-filters/blob/cd3dbcd827aad68fd1399f31d91d54a6adf67ea0/rest_framework_filters/backends.py#L43

**Comment by rpkilby** [comment]
This should have been fixed by ed0977b2afc3dee00d334dfc6370ba1f6e8f310e
