### ISSUE TITLE
Get queryset from RelatedFilter after it was applied?

### ISSUE THREAD

**Issue by RobinRamael** [philipn/django-rest-framework-filters#213]
Is it possible to get the filtered queryset from a related filter? 

Say I have models:

```python
class A(models.Model):
    field = models.CharField()


class B(models.Model):
    a = models.ForeignKey(A)
```
and set up filtering for them

```python
class AFilter(filters.FilterSet):
    class Meta:
        fields = ('field',)


class BFilter(filters.FilterSet):
    a = filters.RelatedFilter(AFilter, queryset=A.objects.all())

    class Meta:
        fields = ('a',)
```
And use these in a view:

```python
b_qs = BFilter({'a__field': 'foo'}).qs
```

I was wondering wether there was anyway to get the `A` queryset from the `BFilter` as if I was doing 
```python
a_qs = AFilter({'field': 'foo'}).qs
```
without having to resort to removing `'a__'` from all keys in the query param dict.

**Comment by rpkilby** [comment]
The short answer is no, not currently. However, you may be interested in #199, which creates some new API surface, and reworks how related filtering is performed. eg, once #199 is cleaned up and merged, you'd be able to access the related queryset like so:

```python
BFilter({'a__field': 'foo'}).related_filtersets['a']
```

**Comment by rpkilby** [comment]
Closing this, as there isn't anything actionable. #199 still needs some polishing, but it will cover the described use case and generally seems like the path forward.

**Comment by RobinRamael** [comment]
Thanks!
