### ISSUE TITLE
"ImportError: No module named related" on latest django 1.8

### ISSUE THREAD

**Issue by asermax** [philipn/django-rest-framework-filters#22]
Aparently the `django.db.models.related` module was moved/removed/merged on latest django versions, which causes a import error when trying to use the filter backend.

**Comment by DanielFerreiraJorge** [comment]
Same here

**Comment by bstempi** [comment]
I'll see if I can get some time to put together a PR for this, but I saw this on some other issue:

try:
           from django.db.models.related import RelatedObject as ForeignObjectRel
        except:
          # django 1.8 +
          from django.db.models.fields.related import ForeignObjectRel

That would allow it to work for both Django 1.7 and 1.8.

The other issue:  https://github.com/treyhunner/django-simple-history/issues/156

How they applied the fix:  https://github.com/treyhunner/django-simple-history/commit/c63438635ee00f4eb906d6d7b6bceac06c9febbb

**Comment by philipn** [comment]
This should now be fixed. It looks like I'd forgotten to push a new release to PyPI.
