### ISSUE TITLE
Provide ability to not include filters on ModelViewSet.get

### ISSUE THREAD

**Issue by efagerberg** [philipn/django-rest-framework-filters#223]
I noticed when setting up a filter with all lookup fields on a viewset that all the filters end up in the `get` method. These filters are most likely useless for gets and should not be included as parameters.

```
class Person(filters.FilterSet):

    class Meta:
        model = Node
        fields = {
            'id': '__all__',
            'name': '__all__',
        }
```
A serializer like this
```
class PersonSerializer(serializers.ModelSerializer):
    class Meta:
        model = Person
        fields = ('id', 'name')
```

and finally a viewset like this
```
class PersonViewSet(viewsets.ReadOnlyModelViewSet):

    queryset = Person.objects.all()
    serializer_class = PersonSerializer
    filter_class = PersonFilter
```

If I register this to my urls I would get a route for a list view and a get similar to this `api/person/` and `api/person/{id}`

And if I go to say swagger and check the get Person API out I would notice that I have filter options for the get like this screenshot.
![screen shot 2018-03-28 at 11 48 44 am](https://user-images.githubusercontent.com/7632073/38040681-077df360-327e-11e8-83a7-3c237c90d6b2.png)

The issue here is, get requires an id and you usually do not need more than that, so these filter options are superfluous.

**Comment by rpkilby** [comment]
Hi @efagerberg. Can you provide more details? I'm not following your question.

**Comment by efagerberg** [comment]
Sure thing @rpkilby so say I have this filter I will update the issue

**Comment by rpkilby** [comment]
Thanks for the explanation. This issue isn't specifically related to drf-filters - any filter backend will have its fields present in the options list. Instead, this is most likely an issue with how the schema is generated, or how it's being used by drf-swagger. I can't really help with this, as I haven't used the auto-doc feature. My suggestion would be to raise an issue with drf-swagger.

**Comment by efagerberg** [comment]
Thanks for looking in, I suppose it was presumptuous to assume the schema from swagger was the truth
