### ISSUE TITLE
ComplexFIlterBackend Unable to parse querystring. Decoded

### ISSUE THREAD

**Issue by radiegtya** [philipn/django-rest-framework-filters#225]
when I am running this filter

```
http://localhost:8000/api/units/?filters=(name=gram&code=gr) | (name=k)
```

the result is like this
```
{
    "filters": [
        "Unable to parse querystring. Decoded: '(name=gram'."
    ]
}
```

Please help, btw the units collection have code, and name fields.

**Comment by rpkilby** [comment]
Please read the documentation for the [`ComplexFilterBackend`](https://github.com/philipn/django-rest-framework-filters#configuring-complexfilterbackend), specifically the section on [encoding the querystring](https://github.com/philipn/django-rest-framework-filters#complex-querystring-encoding).

**Comment by rpkilby** [comment]
The short version is, if you're trying to run a query like:

`filters=(title__startswith=Who) | (title__startswith=What)`

It should be encoded like the following:

`filters=%28title__startswith%253DWho%29%20%7C%20%28title__startswith%253DWhat%29`

**Comment by radiegtya** [comment]
Thank u, Sorry for not understanding well the documentation
