### ISSUE TITLE
Add additional example to Complex querystring encoding

### ISSUE THREAD

**Issue by crintus** [philipn/django-rest-framework-filters#228]
https://github.com/philipn/django-rest-framework-filters#complex-querystring-encoding

The part about Complex querystring encoding is not very clear from the perspective of being used in an API. While the final line `Set as the value to the complex filter param (default: filters).` does explain to add the encoded complex querystring to the `filter` param, it is easily missed.

I suggest just adding a sentence below to outline this with an example url showing how it is used in total.

**Comment by rpkilby** [comment]
> I suggest just adding a sentence below to outline this with an example url showing how it is used in total.

Does the example following the instruction not illustrate this well enough?

**Comment by crintus** [comment]
To me at least, it did not. Explaining the encoding was fine, but I ended up missing the last part saying to add the filters param 😓

**Comment by rpkilby** [comment]
Would this have been more noticable?

> * Set as the value to the complex filter param (e.g., `?filters=<complex querystring>`).

If not, I'm happy to take suggestions.

**Comment by crintus** [comment]
Yeah that should work. 👍
