### ISSUE TITLE
Automatic Filter Negation/Exclusion not working

### ISSUE THREAD

**Issue by pavankumar1792** [philipn/django-rest-framework-filters#233]
Tried filter using negation(/api/trackcampaigns/?asin1__iexact!=B018XN37AU)  as described in the docs but it is not working.

**Comment by rpkilby** [comment]
Hi @pavankumar1792. There is too little information to act on here. If you can provide more details, I'd be happy to help you debug this.

**Comment by pavankumar1792** [comment]
Following is the filter class

class CampaignViewFilter(filters.FilterSet):
    class Meta:
        model = Product
        exclude_filters = True
        exclude_suffix = '!'
        fields = {
            'asin1': ['icontains','iexact','istartswith','iendswith',],
            'item_name': ['icontains','iexact','istartswith','iendswith',],
            'marketplace_name': ['icontains','iexact','istartswith','iendswith',],
            'campaign_status': ['icontains','iexact','istartswith','iendswith',],
            'campaign__name': ['icontains','iexact','istartswith','iendswith',],
        }

the url query param (/api/trackcampaigns/?asin1__iexact!=B018XN37AU) but the filter is not working and query returns whole data.
It is working properly for queries with out negation.

Please help me debug or point me to working sample if you have any.

**Comment by rpkilby** [comment]
`exclude_filters` and `exclude_suffix` are not valid `Meta` options. Are you using some additional mixin that alters behavior?

**Comment by pavankumar1792** [comment]
No i am not using any additional minix. I used them after looking it up in stackoverflow. It is not working with out that meta options also.

**Comment by pavankumar1792** [comment]
is there any detailed documentation with multiple examples / scenarios available ?

**Comment by pavankumar1792** [comment]
@rpkilby how to use a field which is generated by serializers.SerializerMethodField() in filters ?

**Comment by rpkilby** [comment]
Filters are related to model fields, not serializer fields.

**Comment by rpkilby** [comment]
At this point, it's not clear to me why the code isn't working. The existing tests pass, so there's no reason for exclusion to not work. If you could, reduce this to a test case and submit it as a pull request. 

Also, double check that there aren't any form validation errors.
