### ISSUE TITLE
Issue with RelatedFilter parameter name replacement

### ISSUE THREAD

**Issue by jsmedmar** [philipn/django-rest-framework-filters#234]
Hey!

When I declare a related filter as `individual`, an extra query parameter `indivpkual` is generated.

What's happening is that `id`  is being replaced with `pk`. I think this is coming from:

https://github.com/philipn/django-rest-framework-filters/blob/a8fb84ba2c71b5881637157990202d8db72c428b/rest_framework_filters/filterset.py#L45

**Comment by rpkilby** [comment]
Hi @jsmedmar, that is quite an amusing bug. Could you give a more complete example of your filtersets?

**Comment by rpkilby** [comment]
Hi @jsmedmar, I'm currently working on the 1.0 milestone and would like to get this bug fixed as part of that release. Do you have a terse example of the two `FilterSet`s?

**Comment by rpkilby** [comment]
Hi @jsmedmar. I've tried recreating this and have been unable to. If you can provide example filtersets that demonstrate the above issue, I'd be happy to work on a fix. Until then, there isn't much I can do.

**Comment by jsmedmar** [comment]
Ryan thanks so much. Sorry I haven’t been able to get back to this.

**Comment by rpkilby** [comment]
No worries. I'm slowly working towards a 1.0 release (fingers crossed, it's only taken three years 😄). If you have the time/capacity to throw some filters/tests at me, I'd be happy to look into the issue further. Otherwise, happy coding.

**Comment by rpkilby** [comment]
I think I've found another example of this. In `tests.testapp.filters.UserFilter`, the generated filtername is `postss` insteasd of `posts`.

**Comment by rpkilby** [comment]
So, the generated name (`posts`), is having it's `field_name` (`post`), replaced by it's declared name (`posts`), resulting in `postss`.

**Comment by rpkilby** [comment]
I'm still not sure how your case is occurring though. It sounds like your setup is something like:

```python
class MyFilterSet(FilterSet):
    id = RelatedFilter('SomeRelatedFilter', field_name='pk)

    class Meta:
        model = MyModel
        fields = ['id']
```

However, the generated filter name should just be the given field name (`id`). Are you overriding `FilterSet.get_filter_name` to convert `id` to `individual`?

**Comment by jsmedmar** [comment]
these are the filter names autogenerated that im skipping:

    skip = {"indivpkuals", "indivpkual", "pkentifier", "leukpk"}

individuals, individual, identifier, leukid

will post tomorrow the actual Filters

Will share to

**Comment by rpkilby** [comment]
Okay, I think I've figured it out.

Under the hood, `FilterSetMetaclass.expand_auto_filters()` is using `FilterSet.get_filters()` to generate the per-lookup filters for declared `RelatedFilter`s (and any `AutoFilter` subclass). However, the declared filters are currently left on the class, so the result of each call to `get_filters()` is the set of per-lookup filters + all of the declared filters. The declared filters are the problem.

The above then interacts with:
```python
for gen_name, gen_f in new_class.get_filters().items():
    gen_name = gen_name.replace(f.field_name, name, 1) 
```

The above loop is intended to operate on just the generated filters, to replace the model field name with the filter's param name. e.g., the underlying model field name might be `post`, but the exposed param name might be `article`. So, the params should be `article`, `article__in`, etc...

However, this breaks down for partial matches on the declared filters. e.g., post/posts. `get_filters()` returns both a generated `post` `ModelChoiceFilter` as well as the declared `posts` `RelatedFilter`. These are then renamed to `posts` and `postss`. I think this is also what's happening with `individual`, `identifier`, etc... You have something like:

```python
class MyFilter(FilterSet):
    pk = AutoFilter(field_name='id')
    individual = CharFilter()
```

What was throwing me off was `id`/`pk`, which doesn't make sense as a `RelatedFilter`, but would make sense as an `AutoFilter`.

**Comment by jsmedmar** [comment]
Here some examples:

```python
    ...
    # WARNING! haha if pk goes first than id - doing pk="string" raises error
    id = AllLookupsFilter(field_name="id")
    pk = AllLookupsFilter(field_name="id")
    identifier = AllLookupsFilter(field_name="identifier")
    individual = RelatedFilter...
    individuals = RelatedFilter...
    ...
```

This was a funny error, but who knows where that problem comes from:

> # WARNING! haha if pk goes first than id - doing pk="string" raises error
