### ISSUE TITLE
Support for Django 2.1

### ISSUE THREAD

**Issue by sassanh** [philipn/django-rest-framework-filters#238]
Looking at the main page of the repo and considering it's been inactive for a while I'm wondering if django 2.1 will be supported or not.
Currently it's raising this exception when used with django 2.1b1:
```
Could not import 'rest_framework_filters.backends.DjangoFilterBackend' for API setting 'DEFAULT_FILTER_BACKENDS'. ImportError: cannot import name 'QUERY_TERMS'.
```
Also regarding this issue: https://github.com/philipn/django-rest-framework-filters/issues/179#issuecomment-325272715 that led me to use drf-filters in a big project I'm wondering what's the state of this project. Are there any plans to release version 1?

Thanks for the great work so far.

**Comment by rpkilby** [comment]
Ah... right. django-filters doesn't support Django 2.1b1 yet. That `ImportError` would be fixed in https://github.com/carltongibson/django-filter/pull/921.

**Comment by sassanh** [comment]
@rpkilby thanks for making things clear and for making master branch compatible with latest version of Django. It'll solve my problem as I need some new features in django 2.1 and am planning to upgrade to it as soon as it's released.

**Comment by rpkilby** [comment]
It turned out that the master branch was already compatible - the issue was just with django-filter. If you install the branch from https://github.com/carltongibson/django-filter/pull/921, everything should work. I just ran the test suite against that branch, and all tests passed.

**Comment by sassanh** [comment]
Great, thanks.

**Comment by carltongibson** [comment]
https://github.com/carltongibson/django-filter/commit/ce047192749d09b01a59893801820cb255d9cdab

**Comment by rpkilby** [comment]
@carltongibson - thanks for getting 2.x out the door. Glad to finally see that released. 

Now I have don't have an excuse for not finishing the 1.0 milestone 😄

**Comment by rpkilby** [comment]
I'm actively working on the 1.0 milestone today, but the master branch should now be Django 2.1 and django-filter 2.0 compatible. Let me know if you run into any issues.

**Comment by sassanh** [comment]
Yeah the master branch is working for me. Thanks a lot. Looking forward for 1.0 version :-)
