### ISSUE TITLE
Not Correctly Handling Timezone Aware Times

### ISSUE THREAD

**Issue by cancan101** [philipn/django-rest-framework-filters#24]
This datetime does not seem to parse correctly: `2010-1-2T23:18:23.861723Z` even though [DRF handles the format](https://github.com/tomchristie/django-rest-framework/blob/ecb3ba5e1febedb817069affa8ec57b316096504/rest_framework/fields.py#L880-L884).

See also: http://www.django-rest-framework.org/api-guide/fields/#datetimefield

**Comment by philipn** [comment]
I don't know off the top of my head, but I believe I added added in special date time handing here as, at the time, DRF was incapable of correctly parsing ISO 8601 formatted times.

**Comment by philipn** [comment]
@cancan101 You may want to investigate here: https://github.com/philipn/django-rest-framework-filters/blob/master/rest_framework_filters/filters.py#L12

We may simply want to remove these definitions, as it appears DRF fixes this issue in its 3.0 release?

**Comment by cancan101** [comment]
I think it's actually Django which handles the datetime parsing: https://github.com/django/django/blob/0ed7d155635da9f79d4dd67e4889087d3673c6da/django/utils/dateparse.py#L84-L109

**Comment by cancan101** [comment]
Something like this (perhaps with a check to see if `'iso-8601'` is in `api_settings.DATETIME_INPUT_FORMATS`):
```python
class DateTimeFormFieldFixed(forms.DateTimeField):
    def to_python(self, value):
        try:
            return super(DateTimeFormFieldFixed, self).to_python(value)
        except ValidationError as ex:
            if ex.code != 'invalid':
                raise
            try:
                result = parse_datetime(value)
            except ValueError:
                raise ValidationError(self.error_messages['invalid'], code='invalid')
            if result is None:
                raise
        return from_current_timezone(result)


class DateTimeFilterFixed(DateTimeFilter):
    field_class = DateTimeFormFieldFixed
```
