### ISSUE TITLE
Boolean filters don't work as expected

### ISSUE THREAD

**Issue by karmux** [philipn/django-rest-framework-filters#25]
[Django REST Framework](http://www.django-rest-framework.org/api-guide/filtering/) says that *When using boolean fields, you should use the values True and False in the URL query parameters, rather than 0, 1, true or false.*

This cannot be achieved with django-rest-framework-filters. Must use 0 or 1 for boolean field filtering. True and False doesn't work.

**Comment by rpkilby** [comment]
Hi @karmux. Can you include an example FilterSet and model?

**Comment by karmux** [comment]
```
class StuffFilter(filters.FilterSet):
    is_active = filters.AllLookupsFilter(name='is_active')

    class Meta:
        model = Stuff


class StuffViewSet(viewsets.ModelViewSet):
    serializer_class = StuffSerializer
    queryset = Stuff.objects.all()
    filter_class = StuffFilter
```

Must use `?is_active=0` or `?is_active=1`. Using false, False, true or True doesn't work.

**Comment by rpkilby** [comment]
Thanks @karmux, I'll start working on a test case.
