### ISSUE TITLE
v0.10.x Python 2.7 support

### ISSUE THREAD

**Issue by kwigley** [philipn/django-rest-framework-filters#253]
Discovered that using `djangorestframework-filters==0.10.2` with Python 2.7 led to:
```
File "/usr/local/lib/python2.7/site-packages/django_filters/__init__.py", line 4, in <module>
    from .filterset import FilterSet
File "/usr/local/lib/python2.7/site-packages/django_filters/filterset.py", line 184
    def __init__(self, data=None, queryset=None, *, request=None, prefix=None):
```
Turns out that 
> [From Version 2.0 Django Filter is Python 3 only. If you need to support Python 2.7 use the version 1.1 release.](https://github.com/carltongibson/django-filter)

**Comment by rpkilby** [comment]
Hi @kwigley. Notice that the error is occurring in django-filter. Most likely, you've unintentionally upgraded to django-filter v2.0, which was just released and is Python 3 only.
