### ISSUE TITLE
Wanted functionality: Allow for OR as well as AND style filtering.

### ISSUE THREAD

**Issue by illing2005** [philipn/django-rest-framework-filters#26]
You mention this in "wanted functionality"
Is this still planned? 
And is there a best practice to achieve OR functionality?

**Comment by philipn** [comment]
A workaround for `OR` is to run two queries and combine their results.  It wouldn't be difficult to implement `OR`, the real question is what the syntax would be.

**Comment by manuelnaranjo** [comment]
There's no need to combine the results, django ORM is smart enough for this you use the | symbol, thing is which syntax you use for the url querystring... why not just using | as Django would use?

**Comment by rpkilby** [comment]
I've done a little bit of thinking on this, and OR logic doesn't really seem feasible without defining a more complex query syntax. Query strings/params don't support groupings, which are necessary for arbitrary combinations of AND and OR queries.

eg,
Let's say that we do have a syntax for indicating OR queries. Simplifying the query as `A & B & C | D `, do we mean `(A & B & C) | D` or `A & B & (C | D)`? Without grouping syntax this is ambiguous, and we would have to implicitly perform one of those strategies.

There's also the feasibility of implementing OR queries on top of django-filter, and I haven't found a trivial way of doing so. Spent a bit of time looking into this, and the methods I came up with either required rewriting `FilterSet.qs()` or `Filter.filter()` in addition to janky filter validation and broken `MethodFilter`s.

**Comment by rpkilby** [comment]
Hey - I'm closing this in favor of #54 as a more comprehensive set-based syntax is currently being discussed there.
