### ISSUE TITLE
Errors on ViewSets with no filterset_class provided

### ISSUE THREAD

**Issue by joshua-s** [philipn/django-rest-framework-filters#261]
## Issue:
This line is causing ViewSets without a `filterset_class` to break: https://github.com/philipn/django-rest-framework-filters/blob/2fba26e4b9ca3cf129a880e6c3efe77461cea11b/rest_framework_filters/backends.py#L33

### It returns:
`TypeError: issubclass() arg 1 must be a class`

## Example ViewSet from my project:
I am using the `rest_framework_filters.backends.RestFrameworkFilterBackend` globally.
```python
class SavedSearchViewSet(viewsets.ModelViewSet):
    """
    View or edit saved searches.
    """
    queryset = models.SavedSearch.objects.all()
    serializer_class = serializers.SavedSearchSerializer
```

**Comment by rpkilby** [comment]
Thanks!
