### ISSUE TITLE
Serialize the possible values for a field

### ISSUE THREAD

**Issue by Sharlock93** [philipn/django-rest-framework-filters#266]
I have been looking for this for sometime now I couldn't find any documentation on it, is it possible to do it?
for example if you override a viewsets list method which has a filterset class, and you write something like this
`self.filterset_class.get_filters()['filed_name'].field.choices` 
it will return the possible values for that field, I was wondering if there is a more straight forward way for doing this? when you use DRF and add a filterset_class, it will add a filter button to the browseable API view so the functionality must be there, isn't there a way to access it more cleanly?

or if FilterSet could for example add an extra action for the DRF router and it could make life easier when you try to build a frontend filtering system.

**Comment by rpkilby** [comment]
Hi @Sharlock93. It really depends on what you're doing here. If you're getting the choices generated by the filter, then this is probably the easiest way. If you're providing `choices` as an argument to a declared filter instance, e.g., 

```python
class MyFilterSet(filters.FilterSet):
    my_field = filters.ChoiceFilter(choices=[...])
```

then it would be simpler to reference those choices by a named variable instead. e.g.,

```python
MY_CHOICES = [...]

class MyFilterSet(filters.FilterSet):
    my_field = filters.ChoiceFilter(choices=MY_CHOICES)
```

Note that choices can either be a list of two-tuples or a callable.

**Comment by Sharlock93** [comment]
I mean for the choices generated, is it possible to get those generated values along with the 'list' method of the ViewSet, Look at this basic straight forward example:

```python
class Status(Model):
	name = CharField()
	...
class Product(Model):
	status = ForeignKeyField(Status)
	...
....
class ProductFilter(FilterSet):
	class Meta:
		model = Product
		fields = '__all__'

class ProductView(ModelViewset):
	queryset = Product.objects.all()
	serializer_class = ProductSerializer
	filterset_class = ProductFilter
...
router = SimpleRouter()
router.register('products', ProductView)
```

if I do a `GET products/` it will list all the products for me. lets assume If i wanted to build a Filter bar in my front end in angular, I want to have a drop down list that will filter based on the `status` field of the Product model, and I want to populate this drop down list with the possible values for the `status` field.

sure i can make a viewset for the status model too and get the values from there, but I was wondering if there is a way to surface those possible values and `choices` for the status field via an autogenerated api
like if i do 
```
GET products/filter_options/
```
it would return all the possible values for each of the fields, possibly something like this:
```
{
    "status" : [
	{"name": "New"}...
    ]...
}
```

That would greatly help making custom REST API based filters for the frontend frameworks like angular and vuejs

**Comment by rpkilby** [comment]
Your current solution is probably the simplest path to getting the choices. A more general way of doing this in the view would be the following (note that this is for the upcoming 1.0 release):

```python
# For performance, filtersets normally determine a subset of filters to copy, based on the
# request data. Since no data may be provided, you can disable this subsetting behavior.
filterset_class = self.filterset_class.disable_subset()
filterset = filterset_class(queryset=self.get_queryset(), request=self.request)
choices = filterset.filters[filter_name].field.choices
```

I don't know if there's anything that django-rest-framework-filters can/should provide here.

**Comment by Sharlock93** [comment]
Thank you for the input.
