### ISSUE TITLE
Support for Django REST framework 3.2

### ISSUE THREAD

**Issue by maryokhin** [philipn/django-rest-framework-filters#27]
Hello. 

Just tried to upgrade to [Django REST framework 3.2](http://www.django-rest-framework.org/topics/3.2-announcement/), which was released a couple of minutes ago, and this package is the first one that broke. The problem is in the [usage](https://github.com/philipn/django-rest-framework-filters/blob/76fcd3cee38ff9820776b20650bb78b69d81f21a/rest_framework_filters/backends.py#L43-L45) of the deprecated `request.QUERY_PARAMS` instead of the new `request.query_params`. I can write some compat code, but need to know what versions of DRF are officially supported by this package. Most importantly if you plan to support below 3.0.

Maybe adding a tox run with the supported versions would also be good to get a firmer build matrix in place.

**Comment by philipn** [comment]
@maryokhin Thanks for the report! I haven't had a chance to test with DRF 3.2 yet, so this is great to know about. I think it's okay to drop support for versions below 3.0, and require people who want support for DRF < 3.0 to install an older version of this package instead.

**Comment by maryokhin** [comment]
Ok, then from my point what makes sense:
* freeze the current master branch into some kind of `stable/0.3.x` branch and work on master
* Fix 3.2 deprecations
* Release 0.4.0

That way the old version is still available for development in case of a needed critical bugfix.

**Comment by rpkilby** [comment]
@maryokhin Closing this since 0.4.0 has been released.
