### ISSUE TITLE
KeyError  on filter fields

### ISSUE THREAD

**Issue by HVaghinak** [philipn/django-rest-framework-filters#272]
After Upgrading **Django** from 1.11 to 2.0  I was required to upgrade django filters and django rest framework filters. After upgrading I'm getting KeyErrors on all  filter class fields, error occurred in django filter **firlterset.py** file in **filter_queryset** method , in django rest filters **filterset.py** file `self.filters` was overridden with requested_filters but in django_filters in **filter_queryset** method it  going through  `self.form.cleaned_data.items() ` and trying to get all fields from self.filters but because it is overridden it gives KeyError.
django==2.1.1
djangorestframework-filters==0.10.2
djangorestframework==3.8.2
django-filter==2.0.0

**Comment by rpkilby** [comment]
Hi @HVaghinak. Support for django-filter 2.x only exists on the master branch. Please install from there until a new release is cut.
