### ISSUE TITLE
No examples

### ISSUE THREAD

**Issue by hasufell** [philipn/django-rest-framework-filters#279]
The documentation makes little effort to give a comprehensive example and assumes people are familiar with django-filters and django-rest-framework. It gives pretty much no direction on how to create a simple dynamic REST query endpoint to your database model.

**Comment by rpkilby** [comment]
Hi @hasufell. What exactly are you looking for in a comprehensive example? The documentation extensively covers the feature set, and there really isn't much to cover in terms of integration w/ DRF. If a user is familiar with DRF and django-filter, they already know everything they need to hook everything up. It would look something like the below, which is identical to regular django-filter integration:
    
```python
from rest_framework import viewsets
from myapp import filters, models, serializers

class MyEndpoint(viewsets.ModelViewSet):
    queryset = models.MyModel.objects.all()
    serializer_class = serializers.MySerializer
    filterset_class = filters.MyFilter
```

I don't know if there's anything specific to address, but as a new user, it would be great if you could provide advice on what exactly the documentation deficiencies are. PRs are always welcome.

**Comment by rpkilby** [comment]
Closing, as I don't know if there's anything actionable here. Again, PRs welcome.
