### ISSUE TITLE
Timeline for 1.0 final release

### ISSUE THREAD

**Issue by edmorley** [philipn/django-rest-framework-filters#287]
Hi!

We're wanting to soon update to Django 2.1, however doing so requires that we update from django-filters 1.x to 2.x, which in turn throws up this pip warning:

```
djangorestframework-filters 0.10.2.post0 has requirement django-filter~=1.0, but you'll have django-filter 2.1.0 which is incompatible.
```

What steps are left before `djangorestframework-filters` 1.0 final is ready for release, and do you know roughly when that might be? :-)

Many thanks!

**Comment by rpkilby** [comment]
Ach, the 1.0 release has been a *long* time coming. *Only been working on it for ~3 years* 😅 

There are a couple of minor issues that need to be resolved, the only big ticket left is an overhaul of the docs, which is sorely needed. 

That said, 1.0 is mostly ready, and I would recommend trying the [1.0.0.dev0](https://pypi.org/project/djangorestframework-filters/1.0.0.dev0/) release.
- [Here](https://github.com/philipn/django-rest-framework-filters/compare/v1.0.0.dev0...master) are the few changes not included in the dev release.
- [Here](https://github.com/philipn/django-rest-framework-filters/issues?q=is%3Aopen+is%3Aissue+milestone%3Av1.0.0) is what's left on the milestone. Some of this might get bumped (e.g., issue 286).

**Comment by rpkilby** [comment]
Just realizing the above is not a timeline. I'll take a stab at the docs this weekend, and see how far along I can get. That should give me an idea of how much time it should to get an actual 1.0 release out the door.

**Comment by edmorley** [comment]
Thank you for the clarification, that helps :-)

**Comment by rpkilby** [comment]
Quick question - are you able to use the 1.0 pre-release? Have you ran into any issues so far?

**Comment by edmorley** [comment]
Sorry for the delayed reply. We since discovered that the features we were using are now all natively supported by django-filters, so were able to remove the dependency on django-rest-framework-filters, so never got as far as trying the 1.0 pre-release. Thank you anyway :-)

**Comment by markgajdosik** [comment]
Thought I'd comment that we're using 1.0.0-dev0 in production without any issues.

**Comment by rpkilby** [comment]
Thanks - good to know. There are still a few bugs (like rendering the forms in the browsable API w/ crispy forms), but the 1.0 release should largely be ready.

**Comment by HansAarneLiblik** [comment]
Hey, 1.0 is still not released, but your docs currently state, that you're supporting `django-filters` 2.0, but `pipenv graph` states that you don't 

```
djangorestframework-filters==0.11.1
  - django-filter [required: ~=1.1, installed: 1.1.0]
  - djangorestframework [required: Any, installed: 3.9.4]
```

**Comment by rpkilby** [comment]
Hi @HansAarneLiblik. You either need to `pip install -U --pre djangorestframework-filters` or `pip install `djangorestframework-filters==1.0.0.dev0`

**Comment by dralley** [comment]
Hey @rpkilby :D  I hope Portland is treating you well!

Do you expect that it will be ready for a release to PyPI soon? We would love to add some of these features to Pulp but adding a new dependency that has been pre-release for so long is a hard sell.
