### ISSUE TITLE
Support filtering on strings with __in filters

### ISSUE THREAD

**Issue by JockeTF** [philipn/django-rest-framework-filters#29]
The current `__in` filter supports only filtering on integers. There are several cases where I'd like to use an `__in` filter on strings. For example, when looking up several users through the `username` field.

**Comment by sunbest** [comment]
Any example about how to use '__in' ? thx

**Comment by JockeTF** [comment]
The way it works now:

```
GET /users/?id__in=1,2,3
```

I'd like additional support for:

```
GET /users/?username__in=JockeTF,sunbest,philipn
```

**Comment by sunbest** [comment]
How config with filter_class

**Comment by karmux** [comment]
I just hit the same issue. __in filter doesn't work with strings.

**Comment by JockeTF** [comment]
Thank You!
