### ISSUE TITLE
cannot import name 'QUERY_TERMS' again

### ISSUE THREAD

**Issue by jmpmcmanus** [philipn/django-rest-framework-filters#307]
When I install djangorestframework_filters it installs django-filter==1.1,  uninstalling django-filter=2.0. Then when I attempt to import rest_framework_filters I get the following error message:

cannot import name 'QUERY_TERMS' 

I get the same error when I try and import django-filter==1.1. Before I install djangorestframework_filters I am able to import django_filters=2.0.

The readme for djangorestframework_filters says it supports django-filter==2.0, why is it uninstalling it, and installing django-filter==1.1?

Thanks
Jim

**Comment by jmpmcmanus** [comment]
When I download djangorestframework_filters from github and install it using "python setup.py install" I do not have this problem. Using "pip install djangorestframework_filters" appears to be installing an older version, that requires an older version of django-filter.

**Comment by rpkilby** [comment]
Hi @jmpmcmanus. The 1.0 pre-release is compatible with django-filter 2.x and can be installed with pip install --pre.
