### ISSUE TITLE
lt gt

### ISSUE THREAD

**Issue by jmpmcmanus** [philipn/django-rest-framework-filters#308]
I'm trying to use lt and gt. My filter is:

```python
import rest_framework_filters as filters
from .models import testdata_Model

class TestdataFilter(filters.FilterSet):
    class Meta:
        model = testdata_Model
        fields = {
            'concentrat':  ['exact', 'lt', 'gt', 'lte', 'gte']
        }

# view
class testdata_View(viewsets.ModelViewSet):
    queryset = testdata_Model.objects.all()
    serializer_class = testdata_Serializer
    filter_class = TestdataFilter
```

when I try:

http://localhost:8000/api/testdata_Model/?concentrat__gt=2

it does not subset the data?

**Comment by rpkilby** [comment]
Hi @jmpmcmanus. Are you using the `RestFrameworkFilterBackend`?

**Comment by jmpmcmanus** [comment]
I  forgot to put:

    'DEFAULT_FILTER_BACKENDS': (
        'rest_framework_filters.backends.ComplexFilterBackend',
    ),

in settings.py. Now it is working! Thanks!
