### ISSUE TITLE
Update Django Filter Docs

### ISSUE THREAD

**Issue by narendra-kumawat** [philipn/django-rest-framework-filters#310]
Docs saying import FilterBackend that actually not exists in you pip about exist in your repo

**Comment by rpkilby** [comment]
Hi @narendra-kumawat. Please read the readme. 

> ----
> 
> **!** These docs pertain to the upcoming 1.0 release. Current docs can be found [here](https://github.com/philipn/django-rest-framework-filters/blob/v0.10.2/README.rst).
> 
> ----
> 
> **!** The 1.0 pre-release is compatible with django-filter 2.x and can be installed with
``pip install --pre``.
> 
> ----

**Comment by narendra-kumawat** [comment]
@rpkilby Thanks man
