### ISSUE TITLE
Search Inside JSON field

### ISSUE THREAD

**Issue by rjsnh1522** [philipn/django-rest-framework-filters#330]
I have a json field like 
```
record 1 = group_name: {
   "id": 2,
   "name" :"G1"
}
record 2 = group_name: {
   "id": 2,
   "name" :"G1"
}
record 3 = group_name: {
   "id": 1,
   "name" :"G0"
}

```
I need to fetch all the records which has name "G1" case insensitive.
I have tried sending "**group_name__name__in**" but its not working. I need to fetch multiple records with names.

can you explain ?

**Comment by rjsnh1522** [comment]
any update on this?

**Comment by rpkilby** [comment]
Hi @rjsnh1522. JSON filtering isn't something that's provided by drf-filters. You should look at the issues on django-filter for more clarity.
