### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by larsrinn** [philipn/django-rest-framework-filters#340]
We're thinking about integrating a package to simplify filtering in APIs. It seems like this project is abandoned? A bunch of open issues, no release in more than a year, incompatibility with the later releases of Django. 

Does anyone have a recommendation for another project?

**Comment by snowman2** [comment]
https://django-filter.readthedocs.io/en/master/guide/rest_framework.html

**Comment by rpkilby** [comment]
Yes. The tl;dr is that I've been worn out for a while and just haven't had the capacity to keep up with my various open source contributions. I'll be pushing out a 1.0.0.dev1 release shortly that ensures compatibility with django-filter 2.3 and Django 3.0 & 3.1

**Comment by twbagustin** [comment]
Same question now in 2024?
