### ISSUE TITLE
Circular RelatedFilter configuration? Impossible?

### ISSUE THREAD

**Issue by mlissner** [philipn/django-rest-framework-filters#48]
I have a database of judges each of whom have degrees from specific schools. 

I want to use my API to either query judges that went to a specific school:

    /api/judges/?educations__school_name=vanderbilt

Or I want to filter which judges went to a specific school:

    /api/schools/?judges__race=black

I can set up a `RelatedFilter` on one of these, but when I set it up on the second one, it can't find the class.

This problem is handled in Django models by allowing strings for ForeignKey names:

     appointer = models.ForeignKey(
        'Politician',
    )

Is there a way to do this with Django filters?

Thanks for the great package.

**Comment by mlissner** [comment]
Following up to this, I'm trying this for a separate model and realizing that it doesn't work because of circular import errors between to `filters.py` files that I've created (one for each model). 

Seems like a big gap, so I'm hopeful that there's a way to make this work.

**Comment by philipn** [comment]
Did you see the information at the end of the readme on recursive filters? E.g. filters.RelatedFilter('people.views.PersonFilter', name='best_friend')

If this stopped working then it may be a regression.

**Comment by mlissner** [comment]
I feel like an idiot. I looked everywhere for this answer. Except the readme, dang it. Anyway, PR sent to tweak the readme. I figure if I screwed this up, other people will too.
