### ISSUE TITLE
FilterSet.fix_filter_field not called for ALL_LOOKUPS dictionary style declarations

### ISSUE THREAD

**Issue by kewama** [philipn/django-rest-framework-filters#49]
The docs imply that ALL_LOOKUPS dictionary style declarations are equivalent to use of filters.AllLookupsFilter:

     ...we sometimes want to allow any possible lookups on particular fields. We do this by using AllLookupsFilter:
    <snip>
    Additionally, you may use ALL_LOOKUPS with dictionary style declarations.

However, these two approaches are not equivalent because the dictionary approach with ALL_LOOKUPS does not call FilterSet.fix_filter_field method to make filter field / lookup adjustments. That method is only called when the filter is as actually an instance of filters.AllLookupsFilter.

```python
class FilterSetMetaclass(filterset.FilterSetMetaclass):
    def __new__(cls, name, bases, attrs):
        new_class = super(FilterSetMetaclass, cls).__new__(cls, name, bases, attrs)
    
        # Populate our FilterSet fields with all the possible
        # filters for the AllLookupsFilter field.
        for name, filter_ in six.iteritems(new_class.base_filters.copy()):
            if isinstance(filter_, filters.AllLookupsFilter):
                model = new_class._meta.model
                field = filterset.get_model_field(model, filter_.name)
    
                for lookup_type in django_filters.filters.LOOKUP_TYPES:
                    if isinstance(field, ForeignObjectRel):
                        f = new_class.filter_for_reverse_field(field, filter_.name)
                    else:
                        f = new_class.filter_for_field(field, filter_.name)
                    f.lookup_type = lookup_type
                    f = new_class.fix_filter_field(f)
```

**Comment by rpkilby** [comment]
Great catch. I am currently working on a fix/tests.
