### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by edmorley** [philipn/django-rest-framework-filters#53]
I can't seem to find a changelog - either in the readme, as a separate file in the repo or detailed at https://github.com/philipn/django-rest-framework-filters/releases

Please could we add one? :-)

**Comment by rpkilby** [comment]
I'll get around to this at some point. For future reference: http://keepachangelog.com/
In the mean time, 


## CHANGELOG

Unreleased:
- #49 Fix `ALL_LOOKUPS` shortcut to obey filter overrides (in, isnull) 
- Drops support for Django 1.7

v0.6.0: 
- #43 Adds a filter exclusion/negation syntax. eg, `?some_filter!=some_value`
- #44 Sets the minimum django-filter version required

v0.5.0:
- #38 Rework of related filtering, improving performance (#8) and some minor correctness issues
- #35 Add `ALL_LOOKUPS` shortcut for dict-style filter definitions
- #31 Fix timezone-aware datetime handling
- #36 Fix '__in' filter to work with strings
- #33 Fix RelatedFilter handling to not override existing isnull filters
- #35 Fix python 3.5 compatibility issue.
- Drops support for Django 1.6 and below

v0.4.0:
- Adds support for Django 1.8, DRF 3.2
- Drops support for Python 2.6, DRF 2.x
- #23 Adds __in filtering for numeric field types. eg, `?id__in=1,2,3`

**Comment by philipn** [comment]
@rpkilby I've added these notes to the releases page here: https://github.com/philipn/django-rest-framework-filters/releases.  We probably also have `CHANGELOG` file in the repository.
