### ISSUE TITLE
isnull lookup got broken

### ISSUE THREAD

**Issue by TeoTN** [philipn/django-rest-framework-filters#59]
Hello,

After upgrading the library from 0.3.1 to 0.6.0 isnull lookup got broken.

Models:
```python
class AcceptanceCriteria(models.Model):
    name = models.CharField(max_length=40, primary_key=True)
    tests = models.ManyToManyField(Test)

class Test(models.Model):
    name = models.CharField(max_length=40)
```

Filterset:
```python
class TestFilter(filters.FilterSet):
    name = filters.AllLookupsFilter(name='name')
    acceptancecriteria = filters.AllLookupsFilter(name="acceptancecriteria__name", distinct=True)

    class Meta:
        model = Test
```

Thrown exception is: **Unsupported lookup 'isnull' for CharField or join on the field not permitted.**
There were some other issues with previous version of library that were presumably solved in 0.6, so I've updated it and came across that problem. Could you help?

Regards,
Piotr

**Comment by rpkilby** [comment]
Hi @TeoTN - what is model and field you were performing the lookup on?

**Comment by TeoTN** [comment]
I'm sorry, I've forgot to mention it. Model is Test and lookup is acceptancecriteria__isnull=True.

**Comment by rpkilby** [comment]
I have a test case [here](https://github.com/rpkilby/django-rest-framework-filters/commit/8732bea9e769a05e029f3890361bdf4935aa349a), but I'm not able to recreate the issue you're having. 

A couple of problems I noticed:
- The `name` field for `AcceptanceCriteria` is not actually nullable, so the query is nonsensical - it will always turn up empty. 
- If you do make the pk nullable

  ```py
  class AcceptanceCriteria(models.Model):
      name = models.CharField(max_length=40, primary_key=True, null=True)
      tests = models.ManyToManyField(Test)
  ```

  then Django is unable to do a reverse m2m query on the model, and raises:

  ```py
  ValueError: "<AcceptanceCriteria: AcceptanceCriteria object>" needs to have a value for field "acceptancecriteria" before this many-to-many relationship can be used.
  ```

**Comment by rpkilby** [comment]
Hi @TeoTN. The 0.12.0 release of django-filter exposed some bugs in our code, which should now be fixed. Could you install the master branch and verify that the exception is fixed?

**Comment by rpkilby** [comment]
Worth mentioning - an existing test failed with the same exception when upgrading to the 0.12.0 version of django-filter. The changes just pushed to master fixes these issues, bringing the behavior back to what's expected.
