### ISSUE TITLE
Unexpected keyword argument cache

### ISSUE THREAD

**Issue by snewcomer** [philipn/django-rest-framework-filters#69]
After upgrading past 0.4.0, I get an error when filtering on a queryset...

`got an unexpected keyword arguments cache`

Is there some configuration I am missing?  I am using a generic view set and on django rest 3.3.2.

https://github.com/philipn/django-rest-framework-filters/blob/68efb74dd021e2a38faf5817a6463188f73c83b3/rest_framework_filters/backends.py#L15

https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/filters.py#L85

**Comment by rpkilby** [comment]
Hi @snewcomer. Most likely, you're inheriting from `django_filters.FilterSet` instead of `rest_framework_filters.FilterSet`. By default, any unrecognized keywords are passed to the underlying form Field, which is probably what's raising the error.

**Comment by snewcomer** [comment]
@rpkilby so I should have mentioned I am using the standard django orm, basically calling 

`queryset.filter(**kwargs) where kwargs may be {'name__icontains': 'foo'}`

This is probably my problem....

**Comment by rpkilby** [comment]
I'm a little confused as to the usage. If you're not using FilterSets, there would be no need to use the backend. Could you provide a more complete example of the view, filterset, etc..?

**Comment by snewcomer** [comment]
Yep this is my mistake.  Thanks for pointing it out.  I'll have to figure out why we aren't using this great package!
