### ISSUE TITLE
Using django_filters BooleanWidget breaks the rest framework browsable API

### ISSUE THREAD

**Issue by blaze33** [philipn/django-rest-framework-filters#71]
Because it does not implement the `render` method. I also reported the issue to django-filters: https://github.com/carltongibson/django-filter/issues/383

I see that the BooleanWidget was introduced to fix issue #25 by commit https://github.com/philipn/django-rest-framework-filters/commit/d3fd92b842d46a07007d7ca82d58db7c236ce353 but I'm unable to reproduce issue #25 when using django.forms.BooleanField with its the default widget CheckboxInput (ie. querying `?is_active=True`, `?is_active=false`, etc. works just fine, on the contrary it's using `0` or `1` that doesn't work as it evaluates to `bool("0")` or `bool("1")` which is always true. So we cool just get rid of the `BooleanWidget` if we're ok with just using True of False string in queries.

A better solution would be to have a `BooleanWidget` inheriting from both `django.forms.widget.CheckboxInput` for the `render` method and `rest_framework.fields.BooleanField` for the `value_from_datadict` method logic:

```python
from rest_framework.fields import BooleanField
from django.forms.widget import CheckboxInput

class BooleanWidget(BooleanField, CheckboxInput):
    def value_from_datadict(self, data, files, name):
        if name not in data:
            # A missing value means False because HTML form submission does not
            # send results for unselected checkboxes.
            return False
        value = data.get(name)
        return self.to_internal_value(value)
```

And this widget coundn't be in django-filters as it doesn't depend on the rest framework but here in django-rest-framework-filters.

I'm using:
```
Django==1.8.9
django-filter==0.12.0
djangorestframework==3.3.2
djangorestframework-filters==0.7.0
```

**Comment by rpkilby** [comment]
Closing this based on the discussion in 383.
