### ISSUE TITLE
AllLookupsFilter does not work w/ FilterSet mixins

### ISSUE THREAD

**Issue by NotSqrt** [philipn/django-rest-framework-filters#82]
Hi !

cf https://docs.djangoproject.com/en/1.9/topics/db/models/#abstract-base-classes

Is there an equivalent for FilterSets ?

When I do:
```python

class FilterMixin(FilterSet):
    common_field = AllLookupsFilter('field_name')

   # no possibility to do:
   # class Meta:
   #    abstract = True

class ActualFilter(FilterMixin, FilterSet):
    # other filters
    class Meta:
        model = MyModel
```
I get an error :
```
  File "rest_framework_filters/filterset.py", line 57, in __new__
    field = filterset.get_model_field(model, filter_.name)
```

If I do ```class FilterMixin(object): ..```, the common filters are not detected.

I would really like not having to repeat the fields multiple times !

Thanks !

**Comment by rpkilby** [comment]
Hi @NotSqrt 

> cf https://docs.djangoproject.com/en/1.9/topics/db/models/#abstract-base-classes

> Is there an equivalent for FilterSets ?

No, django-filter is a very similar abstraction to standard django forms and is in fact built on top of them. There are no abstract `Form`s, no abstract `FilterSet`s.

Could you provide a more complete stack trace? That's not enough information to go off of.

**Comment by NotSqrt** [comment]
Here is a longer trace:
```
Traceback (most recent call last):
  File "mycode.py", line 34, in <module>
    class MessageMixin(FilterSet):
  File "env/rest_framework_filters/filterset.py", line 57, in __new__
    field = filterset.get_model_field(model, filter_.name)
  File "env/django_filters/utils.py", line 43, in get_model_field
    opts = model._meta
AttributeError: 'NoneType' object has no attribute '_meta'
```

when my code looks like:

```python
class MessageMixin(FilterSet):
    common_field = AllLookupsFilter('field_name')

    # no model in Meta class, this is a mixin

class ActualFilter1(MessageMixin, FilterSet):
    # other filters
    class Meta:
        model = MyModel1

class ActualFilter2(MessageMixin, FilterSet):
    # other filters
    class Meta:
        model = MyModel2
```

The exception is raised at import time, so ``runserver`` or anythong else fails immediately.

If I simply do:

```python
class MessageMixin(object):
    common_field = AllLookupsFilter('field_name')

class ActualFilter1(MessageMixin, FilterSet):
    # other filters
    class Meta:
        model = MyModel1

class ActualFilter2(MessageMixin, FilterSet):
    # other filters
    class Meta:
        model = MyModel2
```

the ``common_field`` filter is not usable.

Whereas for modelforms, it works perfectly to do:
```python
class FormMixin(ModelForm):
    common_field = AllLookupsFilter('field_name')

    # no model in Meta

class ActualForm1(FormMixin):
    # other filters
    class Meta:
        model = MyModel1

class ActualForm2(FormMixin):
    # other filters
    class Meta:
        model = MyModel2
```

**Comment by NotSqrt** [comment]
In django's ``ModelFormMetaclass.__new__``, there's a ``if opts.model: # If a model is defined, extract form fields from it.`` code branch.

**Comment by rpkilby** [comment]
Ah, that makes more sense. Checking for the presence of the model is the right thing to do here.

**Comment by rpkilby** [comment]
Alright, this should be fixed on master - it was a straightforward change.

**Comment by NotSqrt** [comment]
Great ! Thanks !
