### ISSUE TITLE
Investigate using simplified django-filter dict definition

### ISSUE THREAD

**Issue by philipn** [philipn/django-rest-framework-filters#9]
C/o @slafs, https://github.com/alex/django-filter/pull/162 will probably simplify our code here.

**Comment by rpkilby** [comment]
Hi @philipn. Do you think there's anything left to investigate here, or do you think we can close this? Thoughts:
- Handling exists for easily adding all lookups
- Related filters don't work well here, as you need to pass the filterset class to the filter constructor. We could add special handling, but at that point not much is really being gained.

**Comment by philipn** [comment]
Yup, totally agree. Closing this to avoid issue clutter.
