### ISSUE TITLE
Problem with Django 1.9

### ISSUE THREAD

**Issue by saeschdivara** [philipn/django-rest-framework-filters#92]
Hi

I have seen that your Django version is 1.8+ though with Django 1.9.7 I get the following error message:
rest_framework_filters/filterset.py", line 12, in <module>
    from django.utils.datastructures import SortedDict
ImportError: cannot import name 'SortedDict'

Can you please fix that?

**Comment by rpkilby** [comment]
Hi @saeschdivara - it looks like you're using a very outdated version of drf-filters (0.2.2?) that is not compatible Django 1.9. Please update to a newer version.

**Comment by saeschdivara** [comment]
Thanks @rpkilby. Though I think it would be better if the description on pypi.python.org would say more because to me it was confusing that there exist 2 entries with almost the same name.

**Comment by rpkilby** [comment]
> it was confusing that there exist 2 entries with almost the same name.

Could you explain what you mean in more detail?
