### ISSUE TITLE
Combining filters in query parameters (e.g. color=green&color=blue)

### ISSUE THREAD

**Issue by jsmedmar** [philipn/django-rest-framework-filters#93]
Wondering why `django-rest-framework-filters` does not support using multiple values for the same field like `color=green&color=blue`. In that case, I'm only getting `blue` results instead of `blue` + `green`.

This functionality is supported in `django_filters`...

Is it possible to make my filters support this?

**Comment by rpkilby** [comment]
Hi @jsmedmar! Could you provide a more complete example of your filterset and model? There isn't any reason for this to not work. 

The multi-syntax is only supported by the `MultipleChoiceFilter` and `ModelMultipleChoiceFilter`. The former needs to be explicitly declared on the filterset, and the latter is generated for reverse foreign relations. 

There is also a comma-separated value filter that can be generated for `in` lookups. eg, `color__in=blue,green`.

**Comment by jsmedmar** [comment]
My bad for an incomplete example.

My fields are not MultipleChoiceFields, just regular fields with choices... Therefore I think the MultipleChoiceFilter might not work for me.

Wondering if the `color__in=blue,green` is usable right away or if I need to add a AllLookupsFilter? Does this work for reverse relationships?

Thank you very much for your quick response

**Comment by rpkilby** [comment]
Just to clear up any misconceptions about the various filters and fields:
- `ChoiceFilter`/`MultipleChoiceFilter` work with regular model fields that have `choices`. The only difference is that the `multiple` version allows you to filter for multiple values using the `color=blue&color=green` syntax. The standard `ChoiceFilter` will chose only one value. 
- `AllValuesFilter` works identically to `ChoiceFilter`, except that it pulls its choices from the values stored in the database, not from the field's `choices` argument. There is no multiple equivalent, although there is an open PR to add it. 
- `ModelChoiceFilter` and `ModelMultipleChoiceFilter` are intended to work across relationships. Their choices are pulled from the DB, similar to `AllValuesFilter`.

The above filters can be created using the declarative syntax. eg,
```py
# model
class MyModel(models.Model):
    color = models.CharField(choices=(
        ('blue', _('blue')),
        ('green', _('green')),
        ... 
    ))
```

```py
# filterset
class MyFilter(filters.FilterSet):
    color = filters.MultipleChoiceFilter()

    class Meta:
        model = MyModel
```

There is also a [CSV filter](https://django-filter.readthedocs.io/en/latest/ref/filters.html#baseinfilter) base class that is intended to be used as a mixin with more concrete filter types. You could explicitly create this filter, however the `Meta.fields` syntax will automatically create this for you. eg, 

```py
class MyFilter(filters.FilterSet):
    class Meta:
        model = MyModel
        fields = {
            'color': ['exact', 'in', ],
        }
```

This enables you to filter for `color__in=blue,green`. I can't remember if I've tested this with reverse relationships, but there isn't any reason it shouldn't work...

**Comment by jsmedmar** [comment]
Hello @rpkilby Thank you very much!

I tried:

```
color = filters.AllLookupsFilter(name="color")
```

And the `color__in` syntax works as expected!

**Comment by rpkilby** [comment]
Are you sure? The lhs (`color`) corresponds with the query name. If this were your only filter, nothing would happen.

**Comment by Dragonwarrior47** [comment]
how can a define all lookup filter on reverse relation.
I have a model A, and model B
Model B has foreign key to A.

Now I want to have a all lookup filter using in Filter A and want to look for the field which has a foreign key to A in B

**Comment by rpkilby** [comment]
Hi @Dragonwarrior47 - please don't ask unrelated questions in old issues. If you're have a new issue, please open a new issue. Also, it would be helpful to have a more concrete code example. It's not entirely clear what you're looking for.
