### ISSUE TITLE
Query: Abstract filterset

### ISSUE THREAD

**Issue by evenicoulddoit** [philipn/django-rest-framework-filters#94]
I was wondering whether there's a way to apply a FilterSet to a non-generic API View and Django model - i.e. to just apply parsing of GET based filters?

e.g.

```py
# View
class AbstractAPIView(APIView):
    def get(self, request, *args, **kwargs):
        filters = self.get_filters(self.request.query_params)
        custom_api.get_non_model_instances(from_date=filters.from_date)


# Filterset
class AbstractFilterset(filters.Filterset):
    from_date = filters.DateFilter()

# /endpoint?from_date=2016-01-01
```

Where the filterset could just be used to parse the query params, but not be applied to a queryset?

**Comment by rpkilby** [comment]
There wouldn't really be a point of doing this as you'd just be sidestepping the majority of code in django-filter. At this point, it would make more sense for you to just use regular django forms.

**Comment by evenicoulddoit** [comment]
Good point - I should just instantiate a bound form with `request.GET` and use the cleaned data.
